### ISSUE TITLE
What does the mean by "root"?

### ISSUE THREAD

**Issue by zengxiaofei** [DerrickWood/kraken#100]
I used the `MiniKraken DB_8GB` to classify the reads from a red algae. And I found that some reads were "Classified", but the taxonomies were assigned just "root". Should I remove this kind of reads as contamination?

Thank you.
Xiaofei Zeng

**Comment by zengxiaofei** [comment]
Is that means in this read, some kmers were classified into bacteria, some were viruses or archaea, as a result, the read could not be classified into a definite kingdom?

**Comment by Confurious** [comment]
Yes, based on the rules of lowest common ancestor, a fragment classified into different domains of life at the same time will simply not have an actual assignment (in this case "root")

**Comment by jenniferlu717** [comment]
Both comments are correct. Root assigned reads had kmers that belonged in both kingdoms and could not be more specifically assigned.
