### ISSUE TITLE
kraken-build taking forever

### ISSUE THREAD

**Issue by shaman-narayanasamy** [DerrickWood/kraken#101]
Dear authors,

I am attempting to build kraken database for version 1.0:

```
DBNAME="/mnt/nfs/projects/ecosystem_biology/databases/kraken_standard_20171205"

echo "Building database with 72 threads"
date
kraken-build --standard --threads 72 --db $DBNAME
date

echo "Cleaning up database"
date
kraken-build --db $DBNAME --clean
date
```

I am using 72 cores and >700GB of memory. However, regardless of what I do, it is stuck at the following step:

```
Building database with 72 threads
Sun Dec 17 18:36:23 CET 2017
Found jellyfish v1.1.11
Skipping archaea, already completed library download
Skipping bacteria, already completed library download
Skipping viral, already completed library download
Kraken build set to minimize disk writes.
Skipping step 1, k-mer set already exists.
Skipping step 2, no database reduction requested.
Sorting k-mer set (step 3 of 6)...
```
The last run also resulted in the same output. According to additional information, the resource I've allocated is sufficient (https://twitter.com/tomrconnor/status/942721153348620289), but it is not completing anywhere near 5 hours as described in the tweet. 

There is no error being returned, but I do run into my local cluster walltime. When I monitor the process using `htop`, I observe that the process is still running (first one highlighted in blue):

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/4169854/34105377-496b7dac-e3f4-11e7-8597-93bb76538ffb.png">

Is there a mistake in my command. I am following what is written in the manual, with the exception of the number of threads.

I look forward to hearing from you.

Best,
Shaman

**Comment by shaman-narayanasamy** [comment]
Dear all,

I found a workaround thanks to my colleague:

```
DBNAME="/mnt/nfs/projects/ecosystem_biology/databases/kraken_standard_20171205"

echo "Building database with 36 threads"
date
#kraken-build --standard --threads 36 --db $DBNAME

kraken-build --download-taxonomy --db $DBNAME
kraken-build --download-library bacteria --db $DBNAME
kraken-build --download-library archaea --db $DBNAME
kraken-build --download-library viral --db $DBNAME
kraken-build --db $DBNAME --build --threads 36

date
echo "Cleaning up database"
date
kraken-build --db $DBNAME --clean
date
```

Below is the output from my script:

```
Building database with 36 threads
Tue Dec 19 08:57:44 CET 2017
Skipping bacteria, already completed library download
Skipping archaea, already completed library download
Skipping viral, already completed library download
Kraken build set to minimize disk writes.
Skipping step 1, k-mer set already exists.
Skipping step 2, no database reduction requested.
Sorting k-mer set (step 3 of 6)...
K-mer set sorted. [17h26m41.138s]
Skipping step 4, GI number to seqID map now obsolete.
Creating seqID to taxID map (step 5 of 6)...
30256 sequences mapped to taxa. [0.245s]
Setting LCAs in database (step 6 of 6)...
Database LCAs set. [1h36m18.430s]
Database construction complete. [Total: 19h2m59.956s]
Wed Dec 20 04:00:44 CET 2017
Cleaning up database
Wed Dec 20 04:00:44 CET 2017
```

I am still unsure why the full build did not work for me. In any case, I hope someone finds this helpful. Please do not hesitate to inform me in case I did something wrong at the beginning.

Best,
Shaman

**Comment by jenniferlu717** [comment]
Unfortunately the database building does take awhile currently. We are hoping to put a new version out soon (next month or so) which will be faster but it's not yet available. The sorting step does not use multi threads I believe so that is dependent on the number of kmers in the database.
