### ISSUE TITLE
Paired output and file format ignored for the --unclassified-out option

### ISSUE THREAD

**Issue by smdabdoub** [DerrickWood/kraken#102]
For example:

`kraken --fastq-input --gzip-compressed --paired --out-fmt paired --fasta-output --unclassified-out S1_uc --output out/S1_out.txt S1_R1.fastq.gz S1_R2.fastq.gz`

will result in the file `S1_uc` instead of `S1_uc_R1.fastq, S1_uc_R2.fastq`.

The problem is a simple mischeck of the unclassified output file name in the following two lines in classify.cpp: [1](https://github.com/DerrickWood/kraken/blob/1bb596c1508ebbb4c84edb7acea695c35aa6a47f/src/classify.cpp#L124),  [2](https://github.com/DerrickWood/kraken/blob/1bb596c1508ebbb4c84edb7acea695c35aa6a47f/src/classify.cpp#L130) (introduced in 57dddcc).

**Comment by dfornika** [comment]
Mea culpa. Thanks for catching that @smdabdoub.

**Comment by smdabdoub** [comment]
Absolutely, happy to contribute!
