### ISSUE TITLE
Fungi absence

### ISSUE THREAD

**Issue by tantrev** [DerrickWood/kraken#108]
I've just been reading Kraken's documentation, and am curious why fungi aren't included in the standard Kraken database?

**Comment by jenniferlu717** [comment]
It's not a conscious decision to not include it. I believe when Kraken was being developed, fungi was a lot smaller of a category and so the Kraken standard only contains bacteria, viruses, and archaea. We have plans to make the database size smaller in a future release of Kraken and therefore will try to include more of the  Refseq genomes then. If you would like to include them, you can just add all of the genomes to your database and then build the standard.

**Comment by tantrev** [comment]
That makes sense, thank you for the insight!
