### ISSUE TITLE
Problems opening usual fasta files

### ISSUE THREAD

**Issue by tillea** [DerrickWood/kraken#111]
Hi,
the Debian packaged kraken has added a simple test suite that used to work with version 0.10.5 but stoped working since version 1.0.  Some investigation has shown that the fasta examles (for instance

    >gi|441431932| Acartia tonsa copepod circovirus isolate 154_D11, complete genome

can not be read an more due to a to simple parsing algorithm in file _scripts/scan_fasta_file.pl_.

I've added a **very** simple [patch](https://salsa.debian.org/med-team/kraken/blob/master/debian/patches/fix_reading_fasta.patch) to the Debian package which does **not** cover all valid fasta header lines but at least works with the provided examples.
Please provide a more robust method to parse fasta files.  I'd strongly recommend using [bioperl](http://www.bioperl.org/) for this kind of tasks since it has solidly tested and robust code to deal with all kind of sequence formats.
Kind regards, Andreas.

**Comment by dfornika** [comment]
Hi @tillea. Can you post the patch here? The GitLab link doesn't seem to be publicly accessible.

**Comment by dfornika** [comment]
```
Description: Slighly more robust method to obtain taxid of fasta files to at
  least enable reading the provided data examples of autopkgtest
Bug-Debian: https://bugs.debian.org/889623
Forwarded: https://github.com/DerrickWood/kraken/issues/111
Author: Andreas Tille <tille@debian.org>
Last-Update: Wed, 07 Feb 2018 13:41:39 +0100

--- a/scripts/scan_fasta_file.pl
+++ b/scripts/scan_fasta_file.pl
@@ -32,6 +32,8 @@ while (<>) {
   # while (/.../g) needed because non-redundant DBs sometimes have multiple
   #   sequence IDs in the header; extra sequence IDs are prefixed by
   #   '\x01' characters (if downloaded in FASTA format from NCBI FTP directly).
+  s/^>gi\|/>/;
+  s/\| .*//;
   while (/(?:^>|\x01)(\S+)/g) {
     my $seqid = $1;
     my $taxid = krakenlib::check_seqid($seqid);
```

**Comment by tillea** [comment]
Sorry, since I've posted the link the Debian development platform was moved from cgit to gitlab and some deep links are not working any more.  I've fixed the link above (despite you have put a copy here now).  However, my real recommendation would rather be to use  [bioperl](http://www.bioperl.org/) since it would cover all possible flavours of fasta instead of just dealing with the example I was stumbling upon.  I'm not a Perl programmer but its simple enough that I could provide a patch even for this if you agree with the approach in principle.

**Comment by tillea** [comment]
BTW, the problem persists in kraken2 as well.  I wonder why this pretty simple fix is not just applied.

**Comment by jenniferlu717** [comment]
I'm not the  original author of Kraken, just maintaining it for now, so I'm not planning on many changes to Kraken's base code. I would suggest opening an issue on the kraken2 github page.

**Comment by tillea** [comment]
While I understand that you are not the original author you are somehow maintaining the code - at least there was a new release now.  I wonder whether you might consider this pretty simple patch for the next release since it would really help users (outside Debian - the Debian package contains the patch and works like a charm).
Thank you, Andreas.

**Comment by dfornika** [comment]
Hi @tillea I've submitted your patch as a pull-request (#138).

**Comment by tillea** [comment]
On Fri, Aug 02, 2019 at 09:33:14AM -0700, Dan Fornika wrote:
> Hi @tillea I've submitted your patch as a pull-request (#138).
Thanks!

**Comment by jenniferlu717** [comment]
The pull-requests have been merged. Thanks @dfornika
