### ISSUE TITLE
`kraken classify` stuck in D state

### ISSUE THREAD

**Issue by emrahkirdok** [DerrickWood/kraken#115]
I build a *kraken* database for **Archaea-Bacteria-Viral** species (reference and representative genomes) for a test (*k-mer* length:31, minimizer:15).

When I use `kraken classify` with `--preload` switch and 32 cores, program loads the database then stops working. Using `htop`, shows `D` state for all of the 32 instances (some of them changes to `R` and then `D`). I suppose program is working but very very slow (does not classify at all).  

Using *minikraken* database, `kraken` works as expected (same case is true for databases created with smaller *k-mer* sizes).

I am working on a cluster with 32 cores and 1TB memory. My `database.kdb` file is around `250 GB`.

Do you have suggestions?

**Comment by your-highness** [comment]
Hi @emrahkirdok ,

Does your database reside on a network share? The transfer to memory could be slow if the database is very large. 

Make sure that you are allowed to allocate the amount of memory needed for the database with `ulimit -a`. 

Alternatively, try to set up a tmpfs like described in http://ccb.jhu.edu/software/kraken/MANUAL.html#memory-usage-and-efficiency 

Best,

**Comment by emrahkirdok** [comment]
Hi,

No network sharing. 

The problem is that I don't have rights to create a ramdisk in the cluster that I am working. I am trying to figure it out with the help of the cluster admin. Hopefully I will do it soon. Thanks for the help. I will close the issue when I solve this problem.

best regards,

**Comment by mat43672** [comment]
Hi,

Any update on this one? I am facing the same issue, works fast with minikraken, stuck with a 250GB database. 

ulimit seems to return unlimited, no network share. It is within a docker but I have seen the same problem without it in the past and building the database works perfectly.

I cannot see a difference when I use --preload or not, and I wonder whether the preload actually works on my environment as the memory on my server is not filled at all, even though I get the "Loading database... complete" message. 

When building the database on the same machine, it clearly uses the 250gb. I am not an expert with the different kind of memory allocation, I mean when free -m return "250 GB used".

Best

Mathieu

**Comment by emrahkirdok** [comment]
Hi,
I completely forget about this issue. I discussed with system administrators and now they create ramdisk when I need to use Kraken (upon request for now). Now they are trying to find a way to create this ramdisk in a slurm script. I understand that this is the most efficient approach to use Kraken for classification.
