### ISSUE TITLE
Kraken 1.1 still reports as 1.0

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken#117]
Need to update this line?

https://github.com/DerrickWood/kraken/blob/7a9ace070bca0e044ab8f08a5e58d50968017eaa/install_kraken.sh#L22

If you do fix it, please release as Kraken 1.1.1, don't break the 1.1 sha256 - thanks!

**Comment by jenniferlu717** [comment]
Apologies, I haven't had a chance to make all the appropriate fixes. We're working on getting kraken 2.0 out.

**Comment by kapsakcj** [comment]
Just experienced the same thing too. Installed Kraken 1.1, and `kraken --version` returns
```
Kraken version 1.0
Copyright 2013-2015, Derrick Wood (dwood@cs.jhu.edu)
```

**Comment by jenniferlu717** [comment]
Apologies! It should be fixed with this one now......

**Comment by tseemann** [comment]
I always add this test to my conda and brew recipes.
```
test:
   - toolname --version 2>&1 | grep '{{ version }}'
```
Just need a test suite for kraken in TRAVIS that includes this?
