### ISSUE TITLE
taxonomic problem ....

### ISSUE THREAD

**Issue by xgnusr** [DerrickWood/kraken#120]
### kraken output:

65.73  14321   48      D       2           Bacteria
 63.89  13920   74      -       1783272       Terrabacteria group
 63.47  13828   104     P       1239            Firmicutes
 59.76  13020   0       C       526524            Erysipelotrichia
 59.76  13020   0       O       526525              Erysipelotrichales
 59.76  13020   13009   F       128827                Erysipelotrichaceae
  0.02  5       0       -       433334                  unclassified Erysipelotrichaceae
  0.02  5       0       -       544447                    unclassified Erysipelotrichaceae (miscellaneous)
  0.02  5       5       S       1834207                     Erysipelotrichaceae bacterium I46
---------------------------------------------------------------------------------------------
 ... but the real specimen is
Erysipelotrichaceae
Erysipelatoclostridium [Clostridium] innocuum

Can someone help me fix this?

**Comment by jenniferlu717** [comment]
This isn't a problem with Kraken itself but with the taxonomy used. You can manually update the nodes.dmp file in the taxonomy folder but Kraken itself is just going to use what is given. You will need to rebuild if you change the taxonomy.
