### ISSUE TITLE
kraken database build time

### ISSUE THREAD

**Issue by chloelulu** [DerrickWood/kraken#124]
Hi, 
May I know how long does it use to build the kraken database?
I have been running 'kraken-build --download-library bacteria --db bacteria' for  6 days. However, I check the server, it is still running but the database folder has no renewed things since yesterday afternoon.

I check the running history. It is listed as below.
"Downloaded taxonomy tree data
Uncompressing taxonomy data... done.
Untarring taxonomy tree data... done.
Step 1/3: performing rsync dry run...
Rsync dry run complete, removing any non-existent files from manifest.
Step 2/3: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 3/3: Assigning taxonomic IDs to sequences
Processed 269 projects (405 sequences, 678.69 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Step 1/3: performing rsync dry run...
Rsync dry run complete, removing any non-existent files from manifest.
Step 2/3: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 3/3: Assigning taxonomic IDs to sequences
Processed 10905 projects (22717 sequences, 43.58 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Step 1/3: performing rsync dry run...
Rsync dry run complete, removing any non-existent files from manifest.
Step 2/3: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 3/3: Assigning taxonomic IDs to sequences
Processed 7562 projects (9605 sequences, 261.31 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Kraken build set to minimize disk writes.
Creating k-mer set (step 1 of 6)...
Found jellyfish v1.1.11
Hash size not specified, using '22153103360'
K-mer set created. [37h18m17.353s]
Skipping step 2, no database reduction requested.
Sorting k-mer set (step 3 of 6)..."

 Is there anything wrong with me? I am wondering to wait or kill the job.

Thanks.

**Comment by jenniferlu717** [comment]
If you're doing it single threaded, it may take quite a long time. Some of the steps are multithreaded and take far less time than that...It does look like you did it single threaded?

**Comment by chloelulu** [comment]
I see. I will try that.

**Comment by Coaxecva** [comment]
Hi, I got this error after ~20h running kraken-build:

> K-mer set created. [10h4m4.439s]
> Skipping step 2, no database reduction requested.
> Sorting k-mer set (step 3 of 6)...
> K-mer set sorted. [9h47m28.729s]
> Skipping step 4, GI number to seqID map now obsolete.
> Creating seqID to taxID map (step 5 of 6)...
> 49097 sequences mapped to taxa. [0.432s]
> Setting LCAs in database (step 6 of 6)...
> Processed 4762 sequencesxargs: cat: terminated by signal 13
> /backup/qmtran/kraken/build_kraken_db.sh: line 204: 31762 Done                    find library/ '(' -name '*.fna' -o -name '*.fa' -o -name '*.ffn' ')' -print0
>      31763 Exit 125                | xargs -0 cat
>      31764 Killed                  | set_lcas $MEMFLAG -x -d database.kdb -i database.idx -n taxonomy/nodes.dmp -t $KRAKEN_THREAD_CT -m seqid2taxid.map -F /dev/fd/0

Is this because of lack of memory?

Thanks,
Coax

**Comment by jenniferlu717** [comment]
Likely, yes, but we suggest users now switch to kraken2: https://github.com/DerrickWood/kraken2/ which is much better in runtime and in RAM required.

**Comment by sofsta** [comment]
Hello,

I have been running the command 'kraken2-build --build --jellyfish-hash-size --db 'HumanViralBacteria' --threads 4' for three days now. 

How long should I expect to build the kraken database from viral, bacterial and human genomes?

**Comment by jenniferlu717** [comment]
Please make a new issue on the Kraken2 github: https://github.com/DerrickWood/kraken2 

Three days is definitely too long, but two things
1) Kraken2 does not have a --jellyfish-hash-size option 
2) For Kraken 1, it depends on what you are specifying for --jellyfish-hash-size.
