### ISSUE TITLE
Output classifies reads but tax id is zero

### ISSUE THREAD

**Issue by stuber** [DerrickWood/kraken#127]
Using Kraken 2, reads are classified, "C", in output but tax id to label sequence is zero when there is minimal identification.
`C       M00963:162:000000000-AHPVV:1:1101:14752:1397    0       123|123 0:89 |:| 0:15 27592:5 9913:8 0:19 0:22 0:20`

A similar situation using Kraken 1 provides a tax id even with minimal identification.
`C       M00963:162:000000000-AHPVV:1:1101:26396:14957   9606    502     0:80 9606:2 0:127 9606:2 0:10 A:31 0:220`

Is this expected behavior, or is there an option to control this?  I would like all classified reads to have a tax id.

**Comment by DerrickWood** [comment]
Hi @stuber, this is almost certainly a Kraken 2 bug. Can you follow up on the bug I filed in the kraken2 repo (https://github.com/DerrickWood/kraken2/issues/40)? Thanks!
