### ISSUE TITLE
Building Greengenes Database

### ISSUE THREAD

**Issue by AgentKumara** [DerrickWood/kraken#129]
Hello,

I've been trying to build a GreenGenes database, but have seem to hit a problem in the k-mer creation step. The command I'm using is:
`kraken-build --standard --threads 4 --db greengenes`

And I'm getting the following output:
Found jellyfish v1.1.12
Skipping archaea, already completed library download
Skipping bacteria, already completed library download
Skipping viral, already completed library download
Kraken build set to minimize disk writes.
Creating k-mer set (step 1 of 6)...
Found jellyfish v1.1.12
Hash size not specified, using '20045761280'
/Users/agentkumara/anaconda3/envs/kraken/libexec/build_kraken_db.sh: line 96: 87974 Done                    find library/ -name '*.fna' -print0
     87975 Exit 1                  | xargs -0 cat
     87976 Killed: 9               | jellyfish count -m $KRAKEN_KMER_LEN -s $KRAKEN_HASH_SIZE -C -t $KRAKEN_THREAD_CT -o database /dev/fd/0

I'm using anaconda and a Mac. I can't seem to figure out what is causing the error.

**Comment by jenniferlu717** [comment]
Kraken 1.0 does not provide direct support to building a greengenes database. I would switch to Kraken 2.0, which does allow building of the database.
