### ISSUE TITLE
Usage information should reflect KRAKEN_* env vars

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken#13]
The usage information for the kraken* tools should inform the user of the values of ```$KRAKEN_DB_PATH      $KRAKEN_DEFAULT_DB   $KRAKEN_NUM_THREADS``` in the usage information:

     --db NAME               Name for Kraken DB
     --threads NUM           Number of threads

For example, if they are set:

     --db NAME               Name for Kraken DB  (default=/var/db/kraken/minikraken)
     --threads NUM           Number of threads (default=8)

**Comment by DerrickWood** [comment]
Good idea - it's done.
