### ISSUE TITLE
Database Caching

### ISSUE THREAD

**Issue by dcdanko** [DerrickWood/kraken#131]
Not an issue with the existing program just a question.

It sounds like Kraken2 will use much less RAM than Kraken1. However, I've been wondering about adding database caching to Kraken1 (LRU or something similar) and I'm curious if anything like this was ever tried? If so why was it abandoned?

Thanks!

**Comment by jenniferlu717** [comment]
Kraken 2 is the much updated version of Kraken 1, including any and all improvements, so we haven't been adding anything to Kraken 1. I'm not sure if there is any benefit to updating Kraken 1 with our focus being on Kraken 2.
