### ISSUE TITLE
kraken-build NCBI pull problem

### ISSUE THREAD

**Issue by zburcham** [DerrickWood/kraken#132]
It looks like kraken is trying to download "ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_est.accession2taxid.gz” for kraken-build but this is no longer the correct link for the nucleotide accessions. Is there a way to fix this?

**Comment by ArwaAbbas** [comment]
It looks like the error is on NCBI's side. Their README indicates that the "nucl_est.accession2taxid.gz" should exist, but it is pointedly missing in the directory (which was just updated a few days ago).

**Comment by jenniferlu717** [comment]
We have noted this change and hope we can figure out where the file went soon! I think NCBI may have accidentally removed it since (as @ArwaAbbas notes) it is still listed in the README.

**Comment by zburcham** [comment]
They do have the two files "ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz" and "ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_wgs.accession2taxid.gz" if those would work

**Comment by ArwaAbbas** [comment]
I think building the Standard Kraken DB requires those two files _as well_ as the "nucl_est.accession2taxid.gz".

**Comment by jenniferlu717** [comment]
I contacted NCBI and they said that the nucl_est data is now incorporated in the nucl_gb file so we will make changes to the code ASAP.

**Comment by zburcham** [comment]
Thanks! @jenniferlu717 @ArwaAbbas

**Comment by jenniferlu717** [comment]
The code has been updated to fix this issue. The taxonomy download should work now.

**Comment by zburcham** [comment]
Thanks. Does this update apply to the kraken conda package?

**Comment by jenniferlu717** [comment]
Unfortunately not yet. I'm not in charge of changes to kraken conda but will work to make that change happen. I'm hoping to fix some of the download rsync issues before making a new release so that might delay the conda fixes.

**Comment by jenniferlu717** [comment]
Temporary fix for people using conda's version of kraken or kraken2: Run these commands prior to `kraken-build --db . --download-library archaea etc`:

`wget ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz`
`wget ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_wgs.accession2taxid.gz`
`touch accmap.dlflag`

**Comment by SamLambrechts** [comment]
I was wondering, is the fix compatible with the kraken-build --clean command? In other words, can we clean the database after building it? Or does the new structure or some new filenames don't allow that? The reason I ask is because I read a post of somebody who claimed kraken-build --clean removed his whole database, and this was somewhere during or after the recent taxonomy fix (can't remember exactly and don't know exactly how he build his database though)

**Comment by HadrienG** [comment]
PR done for bumping the conda package: <https://github.com/bioconda/bioconda-recipes/pull/14971>
Hopefully it should be merged soon 😄

**Comment by jenniferlu717** [comment]
@zburcham kraken 1 update has been submitted and will be updated (hopefully) soon.

@SamLambrechts Just tested/checked and `--clean` works properly. I don't know what happened to the person who said the whole database was removed.
