### ISSUE TITLE
Re-building the old database

### ISSUE THREAD

**Issue by narsapuramvijaykumar** [DerrickWood/kraken#134]
Hello Team,

My previously database build for bacteria has been deleted and I wanted to re build the same old database using Kraken-build..!!
Is there a scope to do so or else is there a way to download old files from NCBI and build using Kraken..?

Thanks in advance.

Regards,
Vijay N

**Comment by narsapuramvijaykumar** [comment]
Hello Team,

Is there any update on the re-building old database.

Thanks,
Vijay N

**Comment by jenniferlu717** [comment]
Apologies for the late response. All you need to do is delete any "database.*db" files" and lca.complete, and rebuild.
