### ISSUE TITLE
MiniKraken DB_4GB  versus MiniKraken DB_8GB 

### ISSUE THREAD

**Issue by capricy** [DerrickWood/kraken#137]
May I know what is the difference between these two databases?  How many species were included?

Thanks.

C.

**Comment by jenniferlu717** [comment]
Both databases are based on the same sample set. 4GB is just a smaller subset of the kmers (to allow the database to be half the size of the 9GB one).  There are 10,720 species included.

**Comment by capricy** [comment]
Thank you for the information. I wonder how you selected this smaller subset. Also could you please specify how many species in bacteria, archaea and viruses, respectively?
