### ISSUE TITLE
issue with rsync_from_ncbi.pl

### ISSUE THREAD

**Issue by lynngao** [DerrickWood/kraken#157]
Hi, I am downloading the standard database by using this command:
kraken2-build --standard --threads 24 --db $my_directory --use-ftp
and the error message showed like this:
rsync_from_ncbi.pl: unexpected FTP path (new server?) for https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/762/265/GCF_000762265.1_ASM76226v1
Is there any solution for this issue? Thank you so much!

**Comment by ap1438** [comment]
> Hi, i am also getting the same issue. can you please specify how you solved this issue.

**Comment by lynngao** [comment]
> > Hi, i am also getting the same issue. can you please specify how you solved this issue.

See my comment on this
https://github.com/DerrickWood/kraken2/issues/508#issuecomment-938177942
