### ISSUE TITLE
Installation Bug

### ISSUE THREAD

**Issue by pbelmann** [DerrickWood/kraken#17]
Hi,
great job with kraken!
I just want to mention that your install script returns 1 on a successful installation.

It is because of these lines:
```shell
for file in $KRAKEN_DIR/kraken*
do
  [ -x "$file" ] && echo "  $file"
done
```
One of your files you are ckecking is not executable.

best,
Peter

**Comment by DerrickWood** [comment]
Hi Peter,

I think I've fixed this by using an explicit `if` instead of the shorter `&&` form (although I've not been able to reproduce the exit code of 1 for the install script myself).


Derrick
