### ISSUE TITLE
Regarding custom database

### ISSUE THREAD

**Issue by Ramanandan** [DerrickWood/kraken#18]
Dear Derrick,

Thanks for developing kraken pipeline for the scientific community.
I have couple of queries regarding the kraken database.
1) I believe, currently kraken uses RefSeq genomes for bacterial, archael, viral and human. Can I include fungal, plant, nematodes sequences in the database?
2) Instead of RefSeq genomes, can I use RefSeq protein to build my custom database?

Cheers,
Ram

**Comment by Ramanandan** [comment]
Dear Derrick,

Can you please provide some updates on the above query?

**Comment by DerrickWood** [comment]
Kraken supplies explicit support for bacteria, archaea, viruses, and human databases (and combinations thereof). Customized databases, including fungi, plant, or any other genomes are acceptable - you will need to supply those sequences yourself, though. Kraken only works with nucleotide sequences at present.

**Comment by Ramanandan** [comment]
Thanks a lot Dr. Derrick wood for answering my queries.
