### ISSUE TITLE
Building custom database

### ISSUE THREAD

**Issue by Ramanandan** [DerrickWood/kraken#19]
Dear Derrick,

I have installed jellyfish version1.1.11. to build the custom database with fungi, bacteria, and viruses. I followed the instructions in adding libraries to the library folder. 

While at the step of building custom database from the library. I executed below command and I got the following messages in the terminal. I left more than 10 hours. Still I could see only the same message "Hash size not specified, using '12654893177'". 

Is everything fine or am I missing something to build custom database?

wenchenaafc@wenchenaafc:~/metAMOS-1.5rc3/kraken_custom$ kraken-build --build --db customDB --threads 1 --kmer-len 31 --minimizer-len 15 
Kraken build set to minimize disk writes.
Creating k-mer set (step 1 of 6)...
Found jellyfish v1.1.11
Hash size not specified, using '12654893177'

**Comment by DerrickWood** [comment]
Using a single thread may take more than 10 hours to execute the build process. Another important question is whether or not you have enough memory to perform the build - given that you've added some extra genomes to the database's reference library, you may need more than the ~100 GB of RAM needed to build a normal DB.

**Comment by Ramanandan** [comment]
Dear Dr. Derrick,

My current system has 60 GB of RAM. 

I have a query, I downloaded the fasta sequences of fungi from following link ftp://ftp.ncbi.nih.gov/genomes/Fungi/ . After I added all the fasta sequences to library using following command (kraken-build --add-to-library NC*.fa --db customDB), I noticed that inside this location /kraken_custom/customDB/library/added, all the files are in 10 alphanumeric format (e.g. 05uN6lPqey.fna, 4yDCvVze2P.fna..etc). Is that ok?

Once, the custom database has been built what are the output files, I should expect?

**Comment by DerrickWood** [comment]
60 GB is insufficient, and I doubt you'll be able to build the database with that. Fungi, bacteria, and viruses will likely require 100 GB at minimum (depending on how many fungal genomes you added in).

The filenames are fine; Kraken does that as part of the --add-to-library operation. That enables parallel adding of files even if the original filenames conflict.

The output files are the same as with any standard DB (although note again, I don't expect you'll be able to complete the build with 60 GB of RAM).

**Comment by Ramanandan** [comment]
Then I will try in my cluster environment which has more than 500GB. Actually jellyfish version 2 in already installed in the cluster. To down grade to version 1.1.11. takes to lot of time for me to convince the administrator. Let me try and get back to you.

Thanks a lot for your support. Really appreciate it.

**Comment by Ramanandan** [comment]
Thanks Dr. Derrick Wood. 

Successfully, I built the database in my cluster environment by adding Fungal genomes to Bacterial, Viral and plasmids. Database construction process took more than 7 hours. I received following files as output

1) database.idx  --output
2) database.jdb  --output
3) database.kdb --output
4) gi2seqid.map  --output
5) lca.complete  --output
6) seqid2taxid.map --output
7) library folder --input

Do I need to replace the old kraken database with all the above files? or Just with database.idx and database/kdb alone?

**Comment by DerrickWood** [comment]
Of those, the only two you need are the database.idx and database.kdb files. The rest of the output files you listed are used as checkpoints for the build process.

**Comment by libertinerosessanchez** [comment]
Good morning,
After running kraken build, I only have the library and taxonomy folder. Why is it that I don't have the database. idx and database.kdb. I can't run my fasta file since the error says no .kdb file.
This is the commandline I made
kraken-build --standard --threads 16 --db /home/projects/coffee_project/kraken_db
What should I do?

**Comment by jenniferlu717** [comment]
What output did you get from that command line? Did it say which steps were completed?

**Comment by libertinerosessanchez** [comment]
I have the .dmp from taxonomy folder and all the other expected output except for idx and kdb outputs
I have this finished.
Length: 615420 (601K) (unauthoritative)

     0K .......... .......... .......... .......... ..........  8% 86.1K 6s
    50K .......... .......... .......... .......... .......... 16%  185K 4s
   100K .......... .......... .......... .......... .......... 24%  186K 3s
   150K .......... .......... .......... .......... .......... 33%  186K 3s
   200K .......... .......... .......... .......... .......... 41%  185K 2s
   250K .......... .......... .......... .......... .......... 49%  185K 2s
   300K .......... .......... .......... .......... .......... 58%  185K 2s
   350K .......... .......... .......... .......... .......... 66%  185K 1s
   400K .......... .......... .......... .......... .......... 74%  185K 1s
   450K .......... .......... .......... .......... .......... 83%  185K 1s
   500K .......... .......... .......... .......... .......... 91%  184K 0s
   550K .......... .......... .......... .......... .......... 99%  111M 0s
   600K                                                       100% 1900G=3.3s

2018-09-19 14:18:11 (183 KB/s) - ‘all/GCF/002/214/545/GCF_002214545.1_ASM221454v1/GCF_002214545.1_ASM221454v1_genomic.fna.gz’ saved [615420]

FINISHED --2018-09-19 14:18:11--
Total wall clock time: 40m 59s
Downloaded: 278 files, 197M in 24m 17s (139 KB/s)
rsync_from_ncbi.pl: rsync error, exited with code 4
(END)

**Comment by jenniferlu717** [comment]
It looks like it only managed to download some of the standard library files but not all of them (hence the rsync_from_ncbi.pl error). Its an rsync error that occurs on some servers unrelated to Kraken, but the newest version of kraken2 allows for ftp download. 

Try kraken2 if you can [https://github.com/DerrickWood/kraken2]? We are providing more support for kraken2 and have limited support for kraken1.

**Comment by libertinerosessanchez** [comment]
Thank you.

*Libertine Rose S. Sanchez, M.Sc.*
Ph.D. Biology Candidate
Institute of Biology
College of Science
University of the Philippines
Diliman Quezon City 1101
+63 9209203397
