### ISSUE TITLE
The ftp url in download_taxonomy.sh needs to be updated

### ISSUE THREAD

**Issue by arivers** [DerrickWood/kraken#26]
The url for NCBI's ftp site appears to have changed causing the command `kraken-build --download-taxonomy --db name` to fail.

Line 27 of `download_taxonomy.sh` currently reads:
`NCBI_SERVER="ftp.ncbi.nih.gov"`

Changing it to: 
`NCBI_SERVER="ftp.ncbi.nlm.nih.gov"`
and rebuilding Kraken resolved the issue.

Thanks,
Adam

**Comment by DerrickWood** [comment]
Hi Adam,

I'm unable to reproduce this - the existing `ftp.ncbi.nih.gov` name is working fine for me. What failure message are you getting when you try using it?
