### ISSUE TITLE
Having trouble adding the sequences to create a custom database

### ISSUE THREAD

**Issue by sjjose2** [DerrickWood/kraken#30]
Hi - I am trying to build a custom KRAKEN database. I am following all the instructions provided on the manual, but I am not able to add the sequences to the database. Every time I am getting the following error message -"Can't add "/data1/home/sandeep/HMP_Dataset/Simulations/Genomes/CC_121.fa": sequence is missing GI number"

Below are the different modifications I tried on the header of the sequence.

It would be great if you could let me know what be the reason I am getting this error message

> GI:686246107 Staphylococcus aureus ADL-101
> gttacAAGCGCATTTTCGTTCAGTCAACTACTGCCAATATAACTTCGTAGAGCATAGAAC
> ATTGATTTATGTACCAGCCTGATCAACATATAAATATAAATTTTTATGTTTCACGTAAAA
> 
> 686246107 Staphylococcus aureus ADL-101
> gttacAAGCGCATTTTCGTTCAGTCAACTACTGCCAATATAACTTCGTAGAGCATAGAAC
> ATTGATTTATGTACCAGCCTGATCAACATATAAATATAAATTTTTATGTTTCACGTAAAA
> 
> CC_121|kraken:taxid|1308698 Staphylococcus aureus ADL-101
> gttacAAGCGCATTTTCGTTCAGTCAACTACTGCCAATATAACTTCGTAGAGCATAGAAC
> ATTGATTTATGTACCAGCCTGATCAACATATAAATATAAATTTTTATGTTTCACGTAAAA
> 
> kraken:taxid|1308698 Staphylococcus aureus ADL-101
> gttacAAGCGCATTTTCGTTCAGTCAACTACTGCCAATATAACTTCGTAGAGCATAGAAC
> ATTGATTTATGTACCAGCCTGATCAACATATAAATATAAATTTTTATGTTTCACGTAAAA

**Comment by jenniferlu717** [comment]
hi sorry about the very late response. Please refer back to the "Custom Database'' section of the manual: https://ccb.jhu.edu/software/kraken/MANUAL.html
