### ISSUE TITLE
genome sequences for RefSeq bacteria moved on the NCBI ftp

### ISSUE THREAD

**Issue by nicolasnzt** [DerrickWood/kraken#33]
Dear Dr. Wood,

It’s impossible to build new bacteria database using "kraken-build" because the genome sequences for RefSeq bacteria have moved on the ftp as you can see on the NCBI readme file: ftp://ftp.ncbi.nlm.nih.gov/genomes/README.txt

Have you planned to update Kraken  with the new path of the bacteria genomes?

Best regards,
Nicolas

**Comment by douglasgscofield** [comment]
Was just coming here to note the same thing.

Cheers,
Doug

**Comment by DerrickWood** [comment]
I've made a change to the `download_genomic_library.sh` file to point to the archived set of bacterial sequences, which will fix things in the short term. I'm working on a better solution that will allow inclusion of newer sequences as well (that lack GI numbers but have only accession numbers).
