### ISSUE TITLE
set_lcas segfaults with custom database

### ISSUE THREAD

**Issue by fungs** [DerrickWood/kraken#35]
After building a custom database from a single multi-fasta file which I constructed using the described syntax with kraken:taxid header entries, kraken-build (v0.10.5b) fails in step 6:

```
kraken-build --db mydb --build
Kraken build set to minimize disk writes.
Skipping step 1, k-mer set already exists.
Skipping step 2, no database reduction requested.
Skipping step 3, k-mer set already sorted.
Skipping step 4, GI number to seqID map already complete.
Skipping step 5, seqID to taxID map already complete.
Setting LCAs in database (step 6 of 6)...
Processed 108029 sequencesxargs: Prozeß cat wurde durch das Signal 13 abgebrochen.
/net/programs/Debian-7-x86_64/kraken-0.10.5b/bin/build_kraken_db.sh: Zeile 197: 13939 Fertig                  find library/ '(' -name '*.fna' -o -name '*.fa' -o -name '*.ffn' ')' -print0
     13940 Exit 125                | xargs -0 cat
     13941 Speicherzugriffsfehler  | set_lcas $MEMFLAG -x -d database.kdb -i database.idx -n taxonomy/nodes.dmp -t $KRAKEN_THREAD_CT -m seqid2taxid.map -F /dev/fd/0
```

I isolated the respective call and ran set_lcas manually which lead to a simple segfault:

```
set_lcas -x -d database.kdb -i database.idx -n taxonomy/nodes.dmp -t 1 -m seqid2taxid.map -F library/added/1Y0AnEaxod.fna
Processed 108029 sequences
Speicherzugriffsfehler
```

This refers to the same run that is described in issue #34. FASTA headers look like:

```
grep '^>' library/added/1Y0AnEaxod.fna | head
>NZ_AQYU01000016.1|kraken:taxid|35400
>NZ_AQYU01000015.1|kraken:taxid|35400
>NZ_AQYU01000017.1|kraken:taxid|35400
>NZ_AQYU01000014.1|kraken:taxid|35400
>NZ_AQYU01000018.1|kraken:taxid|35400
>NZ_AQYU01000011.1|kraken:taxid|35400
>NZ_AQYU01000010.1|kraken:taxid|35400
>NZ_AQYU01000009.1|kraken:taxid|35400
>NZ_AQYU01000012.1|kraken:taxid|35400
>NZ_AQYU01000008.1|kraken:taxid|35400
```

The taxid is mostly on the species level and I downloaded the latest gi_taxid_nucl.dmp from the NCBI ftp site to be able to run kraken-build on the custom dataset.

**Comment by Sanrrone** [comment]
a solution that works for me (not a best solution), is set --threads 1, first set the flag threads in high number, just for gain speed after crash, then after segment fault, set threads 1 and the works can finish it.

**Comment by fungs** [comment]
@Sanrrone, thanks for the hint but I tried this already and I ran the respective binary set_lcas with one thread (see above posting). Anyway, I came to the conclusion that Kraken is only usable for the precompiled reference data but not for larger custom data due to these bugs. Therefore, I switched over to other software.

**Comment by sridhar0605** [comment]
Is there any solution for this? I am kind off stuck with the same problem

**Comment by fbreitwieser** [comment]
I think the headers should be just '>kraken:taxid|35400', without anything before. Note that you have to delete the seqid to taxid map after changing the files.
