### ISSUE TITLE
make_seqid_to_taxid_map fails when gi2seqid.map is too large

### ISSUE THREAD

**Issue by fungs** [DerrickWood/kraken#36]
In Kraken version 0.10.5b, when fasta sequences and corresponding and gi2seqid.map is large (in my case ~150 k sequences), the binary make_seqid_to_taxid_map fails with std::size_error or similar. I suspect this is due to the integer size type used for the container type?

I simply replaced this step by an awk snipplet followed by GNU `sort -k1,1` which seems to produce identical output.

Gruß Johannes

**Comment by barrantesisrael** [comment]
runnning:

```
$ kraken-build --download-library bacteria --db kraken_DB
$ kraken-build --download-taxonomy --db kraken_DB
$ kraken-build --build --db kraken_DB

```
solved that for me.

**Comment by barrantesisrael** [comment]
runnning:
```
$ kraken-build --download-library bacteria --db kraken_DB
$ kraken-build --download-taxonomy --db kraken_DB
$ kraken-build --build --db kraken_DB
```
solved that for me.

**Comment by fungs** [comment]
@barrantesisrael, only that you seem to solve a different problem. I'm building a database for the gene sequences I have curated and don't want to download a smaller/older one that is provided on the servers. My collection has many more sequences and that is why the mapping file is larger.

**Comment by StackerEd** [comment]
how much memory does your system have?  I believe you can use a --work-on-disk switch that will take much longer to build but even then it might have to load a large concatenated file into memory.  I've had that step running for about 4 days now so I hope mine doesn't crash

**Comment by fungs** [comment]
My system had about 512 GiB of RAM, so that was not the issue.

@StackerEd: if it does with the same error, I can see where I can find the awk code I used to generate the mapping.

**Comment by fungs** [comment]
Anyways, I abandoned Kraken because it seems to be unmaintained.

**Comment by StackerEd** [comment]
that'd be great - I don't plan on abandoning ship as of now, so if this step fails I'd really appreciate any help

**Comment by jenniferlu717** [comment]
We are continuing to update Kraken and are working to improve the memory usage as the databases continues to grow. Our most recent version eliminates dependence on gi numbers.

The next iteration of Kraken and a couple versions that provide more mapping information will be released soon.

**Comment by StackerEd** [comment]
That is an amazing update... I was hoping this would be a feature now that RefSeq has rotated gi numbers out
