### ISSUE TITLE
Identifying Bacillus at the STRAIN level with Kraken

### ISSUE THREAD

**Issue by estyholt** [DerrickWood/kraken#41]
Hello,

I would like to know if it's possible to achieve  **strain-level** sensitivity for Bacillus with Kraken.

Thanks!

**Comment by tseemann** [comment]
Kraken can only identify a strain if genomes from that strain were used to build the database.  It can only compare to what you give it. If your strain is in the database, and has enough unique sequence relative to all the other strains in the database, then yes, it could identify to strain level. How confident you should be in that prediction is not clear.

**Comment by estyholt** [comment]
Thank you!

**Comment by pinghu** [comment]
Did anyone successfully identify the strain level differences using Kraken? I  tried a customized database with different strains and tried two strain's sequences, Kraken's output only shown the taxid associated at the species level, which part should I change to make the output reach strain level? Many thanks!

**Comment by jenniferlu717** [comment]
It depends on which strains. Some strains are just too similar for Kraken to be able to identify the differences between the strains. The read would need to be unique to one strain for classification at the strain level (this is also why we don't provide the option for strain level abundance with Bracken). 

Also, it should be noted that there is inconsistency in how people define new strains vs. new species, making, with some strains more similar than other strains.
