### ISSUE TITLE
Number of distinct kmers mapping to a species

### ISSUE THREAD

**Issue by milkbugdoctor** [DerrickWood/kraken#43]
Q1 . Is it somehow possible to get an output field in the kraken-report  which summarizes the distinct number of non overlapping kmers (or overlapping if the former calculation is complex) that were directly assigned to a particular taxonomic node. This could give an idea about the total amount of coverage one sees for a particular taxonomic node.  While we are at it, for each taxonomic node how about computing the ratio of  observed kmers assigned for the node / total number of  kmer assigned for that node .

Q2. Is there a good strategy to get rid of low complexity kmers ? They are especially troublesome when analyzing meta-transcriptomic data.

**Comment by jenniferlu717** [comment]
Q1: One of the post-docs in our lab is working on a version of Kraken that provides this information while minimizing additional memory usage. Im unsure about the release date of that version however. 

Q2: We use dustmasker from NCBI. its not currently incorportated into the Kraken code but i hope to add this option in the next few weeks.
