### ISSUE TITLE
Problems during installaion

### ISSUE THREAD

**Issue by Lily-WL** [DerrickWood/kraken#44]
### I just started to use Kranken. After the downloading of database, some problem seems to come during building.

_Found jellyfish v1.1.11
tar: citations.dmp：无法将所有权改为 uid 9019，gid 583: 无效的参数
tar: 跳转到下一个头
tar: 归档包含 “\tn\tuncultur” 而需要数字值 off_t
tar: 归档包含 “n\t11\tn\t1” 而需要数字值 mode_t
tar: 归档包含 “don\n350657\tn” 而需要数字值 time_t
tar: 归档包含 “\tn\t0\tn\t” 而需要数字值 uid_t
tar: 归档包含 “\tn\t1\tn\t” 而需要数字值 gid_t
tar: pecies\tn\tUAon\t11\tn\t1\tn\t11\tn\t1\tn\t0\tn\t1\tn\t1\tn\t0\tn\tunculturedon\n350656\tn\t75661\tn\tspecies\tn\tUAon\t11\tn\t1\t：未知的文件类型“  ”，作为普通文件展开
tar: pecies n   UAon    11  n   1   n   11  n   1   n   0   n   1   n   1   n   0   n   unculturedon
350656  n   75661   n   species n   UAon    11  n   1   ：不可信的旧时间戳 1970-01-01 07:59:59
tar: 跳转到下一个头_

_gzip: stdin: invalid compressed data--crc error

gzip: stdin: invalid compressed data--length error
tar: Child returned status 1
tar: Error is not recoverable: exiting now_
### A mail (in /var/spool/mail/root) gave some tips about the problems of the hardware.

 _WARNING: at kernel/rh_taint.c:13 mark_hardware_unsupported+0x39/0x40() (Not tainted)
:Hardware name: ThinkServer RD640  
:Your hardware is unsupported.  Please do not report bugs, panics, oopses, etc.,
 on this hardware._

**Comment by tseemann** [comment]
Your download file is corrupt.
