### ISSUE TITLE
switch from GI to accession

### ISSUE THREAD

**Issue by audy** [DerrickWood/kraken#50]
NCBI is [discontinuing support for GI numbers](http://www.ncbi.nlm.nih.gov/news/03-02-2016-phase-out-of-GI-numbers/) in favor of accession numbers.

There is currently a database of GI -> TaxID available from NCBI's [ftp site](ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/) so moving kraken from GIs to accessions should be easy.

(related to #39)
- Link to FTP: ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/

**Comment by tseemann** [comment]
Supporting genbank files will also not require the conversion to taxid - see issue #51

**Comment by moskalenko** [comment]
Has there been any progress? It doesn't appear possible to build a custom kraken database at this time.

**Comment by audy** [comment]
Hey @moskalenko!

I've had success with https://github.com/mw55309/Kraken_db_install_scripts

Let me know if you hit a snag.

**Comment by pshtiwan** [comment]
Hi all

**Comment by pshtiwan** [comment]
I new in field of metagenomic and i tried  build a custom database with version 010.5  but isnt working with this script kraken-build --download-taxonomy --db $DBNAME  
Is that this script is enough to download GI number.

**Comment by jenniferlu717** [comment]
Kraken v1.0 has taken this into account. All databases built with the newest Kraken version should work despite the phasing out of GI numbers. Sorry for the long wait before this fix.

**Comment by moskalenko** [comment]
Thank you. This is great news.
