### ISSUE TITLE
Support .gbk / .gbff [.gz] files 

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken#51]
It would be great if `--add-to-library` could support `.gbk`/`.gbff` (and `.gz` versions thereof).

These have the taxid in `taxon:NNN` field in the `source` tag.

To make it fast you can avoid parsing the Genbank file, and just read it as follows:

https://raw.githubusercontent.com/MDU-PHL/mdu-tools/master/bin/genbank-to-kraken_fasta.pl

**Comment by dfornika** [comment]
@tseemann 

I've incorporated this suggestion into a branch of my fork:

https://github.com/dfornika/kraken/tree/add-to-library-gb

Do you have any suggestions on how this could be improved before I create a pull request?

**Comment by tseemann** [comment]
@dfornika I've commented on your fork commit with some things.

**Comment by dfornika** [comment]
@tseemann The pull request was merged so I think this issue can be closed

**Comment by tseemann** [comment]
@dfornika ok, i will close. i don't think you amended anything before the acceptance?
