### ISSUE TITLE
paired and unpaired reads

### ISSUE THREAD

**Issue by helloworld44** [DerrickWood/kraken#52]
Hi,
I want to analyze a set of reads with kraken.
After the trimming step of my paired-end data, a part of the reads lost their mates (mate was too short after quality trimming). I obtain a fastq file with the right mate, a fastq file with the left mate and a fastq file with singletons.
Please, could you tell me if is it possible to include all the reads (paired and singleton) in the kraken analysis ? Should I concatenate the files containing right/left paired reads with the file containing unpaired right/left mate or should I run kraken separately for the paired and unpaired reads ?

Thank you in advance for your reply,

**Comment by tseemann** [comment]
I would use `read_merger.pl` on the LEFT and RIGHT files, and join that to the SINGLES file, then give it to kraken all at the same time. Do not use `--paired` mode!

You might be able to do this if you use bash or zsh shell to avoid temporary files:

```
kraken <(cat SINGLE.fq && read_merger.pl R1.fq R2.fq)  
```
