### ISSUE TITLE
new release any time soon?

### ISSUE THREAD

**Issue by Florian-EagleGenomics** [DerrickWood/kraken#53]
Hi there. Your current master code looks fairly stable and has not seen many updates lately, whereas the 0.10.5-beta (the last tagged version) has a build issue. Looking at the commit history this seems to have been fixed very quickly. However, since there is no newer tag, I am stuck with using the master, which I would like to avoid using in my production setup. If there are no reasons against it, could you please release a new version and tag it?
Thanks a lot for a great tool!
Florian

**Comment by lynxoid** [comment]
Maybe Braken (http://biorxiv.org/content/early/2016/05/05/051813) is delaying the update process?

**Comment by cjfields** [comment]
May be some issues with the recent NCBI changes from GI to Accession.Version, see issue #50

**Comment by taltman** [comment]
Thanks for pointing out Bracken, @lynxoid!

**Comment by andzandz11** [comment]
Is kraken still okay? Will it be improved? Does it have support? I am starting a 3 year project and I do not want to start using something that is slowly falling apart, as you can see with the GenBank ID issue.

**Comment by Redmar-van-den-Berg** [comment]
I think kraken will be ok, the original maintainer has moved on but there is still interest in the program, and I've been working on adding support for Accession instead of GI. You can see some discussions about that here (https://github.com/DerrickWood/kraken/issues/68). I think the best course of action is to ask the developer of Bracken if they want to take over support, since their work requires Kraken as well. https://github.com/jenniferlu717/Bracken

**Comment by jenniferlu717** [comment]
Hi, As the developer of Bracken, I was not intending on taking over support of Kraken but our lab in general is working through some upgrades/updates to Kraken. @DerrickWood also has an updated version that should address the GI numbers (from what I have heard).  I'm not sure when we will release the updates but hopefully it will be soon. 

As we still use Kraken within our lab for our projects, we have not abandoned the software but have delayed working on it as Derrick Wood is still the primary owner/developer of the Kraken software.

**Comment by jenniferlu717** [comment]
Derrick just made a fix to the phasing out of NCBI GI numbers so the new version should work properly. If not, please create a new issue and let us know. Thanks,
