### ISSUE TITLE
set_lcas: error opening taxonomy/nodes.dmp: No such file or directory

### ISSUE THREAD

**Issue by wangzhenkeep** [DerrickWood/kraken#55]
what should I do about the error?

Kraken build set to minimize disk writes.
Creating k-mer set (step 1 of 6)...
Found jellyfish v1.1.10
Hash size not specified, using '9096'
K-mer set created. [0.037s]
Skipping step 2, no database reduction requested.
Sorting k-mer set (step 3 of 6)...
K-mer set sorted. [1m46.611s]
Creating GI number to seqID map (step 4 of 6)...
GI number to seqID map created. [0.008s]
Creating seqID to taxID map (step 5 of 6)...
5 sequences mapped to taxa. [0.005s]
Setting LCAs in database (step 6 of 6)...
set_lcas: error opening taxonomy/nodes.dmp: No such file or directory

**Comment by ciemanek** [comment]
I get the same error while trying to build a human database. I used `--download-library` human option and while trying to actually build a db with `--build` I get the following error:

```
Creating sequence ID to taxonomy ID map (step 1)...
Sequence ID to taxonomy ID map complete. [0.163s]
Estimating required capacity (step 2)...
Estimated hash table requirement: 4150018924 bytes
Capacity estimation complete. [2m14.406s]
Building database files (step 3)...
build_db: error opening taxonomy//nodes.dmp: No such file or directory
xargs: cat: terminated by signal 13
```

How could this be approached?

**Comment by jenniferlu717** [comment]
Did you download the taxonomy as well? Is the taxonomy/nodes.dmp file there?

**Comment by ciemanek** [comment]
I just ran `--download-library`, following the note in Kraken2 manual as I am interested in human which is listed as one of the databases that don't require mapping:
![image](https://user-images.githubusercontent.com/50014222/56803555-3b53c300-6823-11e9-8c23-fd0efa6c2bdf.png)

Maybe I misunderstood instructions?

**Comment by ciemanek** [comment]
After trying to use `-download-taxonomy` I also get an error:
`rsync: link_stat "/taxonomy/accession2taxid/nucl_est.accession2taxid.gz" (in pub) failed: No such file or directory (2)`

If I understand correctly from another [issue](https://github.com/DerrickWood/kraken2/issues/101), it's because of some changes in the NCBI files? Is there a way to solve this issue for conda installation?

**Comment by jenniferlu717** [comment]
working on the issue for conda. For now, I would just run these commands: 

`wget ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz`
`wget ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_wgs.accession2taxid.gz`
`touch accmap.dlflag`

and put all of those files into a taxonomy/ folder. 

It's not the best option, but it will work for now until we get the conda version updated.

**Comment by ciemanek** [comment]
Thank you! Should those files be enough to run `--download-library` successfully?

**Comment by jenniferlu717** [comment]
No, but you can run --download-taxonomy and it will skip the problematic lines and download the rest of the taxonomy.

Then you can run --download-library. Sorry this is a lot right now.

**Comment by ciemanek** [comment]
Thanks a lot, that indeed solved the problem :)

**Comment by Marcopterix** [comment]
I downloaded taxonomy directory with: "kraken2-build --download-taxonomy --db my_kraken_db"
 and the problem was solved
