### ISSUE TITLE
classify slow on MacOS Sierra

### ISSUE THREAD

**Issue by rec3141** [DerrickWood/kraken#56]
Kraken is running very slowly after update to MacOS Sierra (from 10.9). Even using 14 threads, 'classify' is only using 2% of CPU resources running on fastq files. Happens when using either RAM or a ramdisk. I also tried re-compiling kraken after the update, no difference. Anyone else had this problem?

**Comment by rec3141** [comment]
ps by 'slow' I mean ~2000 seqs/minute in 'quick' mode

208952 sequences (49.57 Mbp) processed in 7947.301s (1.6 Kseq/m, 0.37 Mbp/m).
  19249 sequences classified (9.21%)
  189703 sequences unclassified (90.79%)
486743 sequences (110.30 Mbp) processed in 18634.380s (1.6 Kseq/m, 0.36 Mbp/m).
  42817 sequences classified (8.80%)
  443926 sequences unclassified (91.20%)
607374 sequences (124.29 Mbp) processed in 20227.920s (1.8 Kseq/m, 0.37 Mbp/m).
  48978 sequences classified (8.06%)
  558396 sequences unclassified (91.94%)
1803458 sequences (362.91 Mbp) processed in 52542.371s (2.1 Kseq/m, 0.41 Mbp/m)..
  97644 sequences classified (5.41%)
  1705814 sequences unclassified (94.59%)
2049109 sequences (341.22 Mbp) processed in 54477.932s (2.3 Kseq/m, 0.38 Mbp/m).
  94811 sequences classified (4.63%)
  1954298 sequences unclassified (95.37%)
1952769 sequences (406.29 Mbp) processed in 56325.936s (2.1 Kseq/m, 0.43 Mbp/m).
  164118 sequences classified (8.40%)
  1788651 sequences unclassified (91.60%)
2552823 sequences (416.05 Mbp) processed in 58791.326s (2.6 Kseq/m, 0.42 Mbp/m).
  209025 sequences classified (8.19%)
  2343798 sequences unclassified (91.81%)
1932294 sequences (422.92 Mbp) processed in 58877.487s (2.0 Kseq/m, 0.43 Mbp/m).
  114113 sequences classified (5.91%)
  1818181 sequences unclassified (94.09%)
2069224 sequences (447.46 Mbp) processed in 60256.734s (2.1 Kseq/m, 0.45 Mbp/m).
  221269 sequences classified (10.69%)
  1847955 sequences unclassified (89.31%)
2625425 sequences (453.21 Mbp) processed in 61245.445s (2.6 Kseq/m, 0.44 Mbp/m).
  318459 sequences classified (12.13%)
  2306966 sequences unclassified (87.87%)
2298633 sequences (471.09 Mbp) processed in 61447.236s (2.2 Kseq/m, 0.46 Mbp/m).
  158384 sequences classified (6.89%)
  2140249 sequences unclassified (93.11%)
1946629 sequences (436.53 Mbp) processed in 62056.084s (1.9 Kseq/m, 0.42 Mbp/m).
  218893 sequences classified (11.24%)
  1727736 sequences unclassified (88.76%)

**Comment by tseemann** [comment]
Does your laptop have SSD or regular HDD?  
How much RAM?
What CPU?

You shouldn't use more `--threads` than you have physical cores.

**Comment by rec3141** [comment]
It's a late 2013 Mac Pro (trashcan) with 8 cores and 128Gb RAM, writing to an SSD. Never had an issue before running up to twice the number of --threads as cores.

**Comment by tseemann** [comment]
What speed do tools like `seqtk fqchk R1.fastq.gz` get?

One outside chance is that your SSD is about to fail, and the slow speed is the SSD remapping failed 'sectors' continuously.

Otherwise I have no idea, your specs are fine.

**Comment by yesimon** [comment]
By default you won't have openmp support on OS X unless you used Homebrew's gcc specifically or clang-openmp. Without openmp it will only use 1 thread.
