### ISSUE TITLE
kraken can't find jellyfish running within an HPCCluster

### ISSUE THREAD

**Issue by GeoMicroSoares** [DerrickWood/kraken#60]
kraken and jellyfish are installed to /kraken_install and /jellyfish-1.1.11 and all directories containing relevant executables have been added successfully to .bashrc
 
```
[ans74@hpc~]$ kraken-build
Must select a task option.
Usage: kraken-build [task option] [options]
 
Task options (exactly one must be selected):
--download-taxonomy        Download NCBI taxonomic information

``` 
```
[ans74@hpc~]$ jellyfish
Too few arguments
Usage: jellyfish <cmd> [options] arg...
Where <cmd> is one of: count, stats, histo, dump, merge, query, cite, qhisto, qdump, qmerge, jf.
Options:
--version        Display version
```
running my script results in:
```
[ans74@hpc ~]$ cat kraken_3*
/hpc/ans74/kraken_install/check_for_jellyfish.sh: line 27: jellyfish: command not found
```
however, running (not submitting) check_for_jellyfish.sh works!
```
[ans74@hpc ~]$ ./kraken_install/check_for_jellyfish.sh
Found jellyfish v1.1.11
```
Also, running the command I am trying to submitting to the HPC manually works:
```
[ans74@hpc ~]$ kraken-build --standard --db /hpc/scratch/ans74/kraken_database/
Found jellyfish v1.1.11
--2017-03-20 15:04:16--  ftp://ftp.ncbi.nih.gov/pub/taxonomy/gi_taxid_nucl.dmp.gz
            => “gi_taxid_nucl.dmp.gz”
Resolving ftp.ncbi.nih.gov... 130.14.250.12, 2607:f220:41e:250::13
Connecting to ftp.ncbi.nih.gov|130.14.250.12|:21... connected.
Logging in as anonymous ... ^C
```
Is this somehow related to how kraken is written?
Does it make any sense that the executables are mapped into the .bashrc and work from there but then the script when submitted isn't able to detect jellyfish from the same directory?

**Comment by tseemann** [comment]
On your HPC cluster script, have you loaded all the modules?
`module load jellyfish/1.1.1` etc?

**Comment by GeoMicroSoares** [comment]
Solution was to add #$ -V to the script in order to load my environment variables to the SGE.

**Comment by pbpayal** [comment]
./kraken-build --standard --db dir/0.10.5/KrakenDB
dir/kraken/0.10.5/check_for_jellyfish.sh: line 27: jellyfish: command not found

Do I need to install jellyfish separately?

**Comment by pbpayal** [comment]
Thanks!!
After installation of jellyfish v1.1.11 
**./check_for_jellyfish.sh | ./kraken-build --standard --db dir/0.10.5/KrakenDB**
And then it works fine.

**Comment by katewd** [comment]
For those who have the same problem I did when using Kraken and Jellyfish: 
I installed jellyfish v1.1.11 using sudo but then couldn't access the library created/needed when running kraken and jellyfish as 'me'. To get around this, I added the following line to my .bashrc file
**export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/**
And then it worked fine.
