### ISSUE TITLE
Better prediction on genome assemblies than reads 

### ISSUE THREAD

**Issue by EliseBIBS** [DerrickWood/kraken#62]
Hello everybody,

I assembled genomes from known species with paired reads. 
Then, i used kraken to confirm the species of my genomes. 
Generally, using kraken on the assembled genomes gives good predictions.
However, using kraken on the reads gives less accurate predictions. 
 
For example, from my kraken output, I have this line :
`C       id  288681  201     86661:3 288681:31 86661:36 A:31 86661:23 0:47`
I don't understand why, for this read, the assigned taxon number is 288681 when a majority of kmers is assigned 86661. Did someone have the same issue ?
Thanks !

**Comment by tseemann** [comment]
288681 is strain specific: Bacillus cereus E33L
86661 is more general Bacillus cereus group

So there was probably statistically enough E33L specific kmers for it to be binned as 33L.

**Comment by jenniferlu717** [comment]
This has to do with Kraken's base algorithm. Kraken tries to give the most specific classification possible.

So for example, if two species A/B are in genus X and 2000 kmers classify at genus X but 30 kmers classify at species A and 2 kmers at species B, Kraken will give a classification of species A.

More generally, Kraken classifies reads at the leaf level of the root-to-leaf path with the most kmers.
