### ISSUE TITLE
kraken doesn't build with latest ncbi genomes

### ISSUE THREAD

**Issue by ajaybabu27** [DerrickWood/kraken#65]
I got the following error when I used [Tomer's fork of kraken](https://github.com/taltman/kraken). This was during building kraken-db:

 Kraken build set to minimize disk writes.
 Creating k-mer set (step 1 of 6)...
 Found jellyfish v1.1.5
 Hash size not specified, using '371226587954'
 terminate called after throwing an instance of
 'jellyfish::invertible_hash::ErrorAllocation'
 what():  Failed to allocate 2611340115968 bytes of memory
 xargs: cat: terminated by signal 13
 /sc/orga/work/kumara22/tools/kraken/build_kraken_db.sh: line 113: 52528
 Done                    find library/ '(' -name '*.fna' -o -name '*.fa' -o -name '*.ffn' ')' -print0
      52529 Exit 125                | xargs -0 cat
      52530 Broken pipe             | dustmasker -outfmt fasta
      52531 Broken pipe             | sed -e '/>/!s/a\|c\|g\|t/N/g'
      52532 Aborted                 (core dumped) | jellyfish count -m
 $KRAKEN_KMER_LEN -s $KRAKEN_HASH_SIZE -C -t $KRAKEN_THREAD_CT -o database /dev/fd/0

Looks like it requires high amount of memory. I am currently running this on a node with 700 GB memory and 32 cores. I don't think kraken can run on multiple nodes.

 Ajay.

**Comment by taltman** [comment]
Hi Ajay,

Just to clarify, this is not an issue specific to my fork. Take a look at the Manual, under the "--jellyfish-hash-size" parameter. The trick that I did was to take the hash size that it reports that it is using by default (in your case, '371226587954'), and then I keep reducing this amount by an order of magnitude until it doesn't choke the machine that I am on.

HTH,

~T

**Comment by ajaybabu27** [comment]
Hi Tomer,

Thanks for the clarification. 

I see that the original Kraken version uses old NCBI genomes and thus I never encountered this glass wall.

In your experience, have you had any reduction in classification performance of kraken by specifying a lower hash size parameter for jellyfish ? (Excuse my naive question due to my unfamiliarity with jellyfish). 

Thanks,
Ajay.

**Comment by taltman** [comment]
Yes, I've been experiencing some scaling issues now that I've fixed the NCBI FTP fetching. 

This won't impact kraken's accuracy, as it just optimizes the runtime performance profile of jellyfish itself. Jellyfish is just an efficient kmer counting tool. Kmers will still get counted as long as you don't exhaust your system memory. See the jellyfish manual for more details.

**Comment by ajaybabu27** [comment]
Thanks Tomer !

**Comment by tseemann** [comment]
*The relevant parts of the manual:*

If you encounter problems with Jellyfish not being able to allocate enough memory on your system to run the build process, you can supply a smaller hash size to Jellyfish using kraken-build's --jellyfish-hash-size switch. Each space in the hash table uses approximately 6.9 bytes, so using "--jellyfish-hash-size 6400M" will use a hash table size of 6.4 billion spaces and require 44.3 GB of RAM.

Kraken's build process will normally attempt to minimize disk writing by allocating large blocks of RAM and operating within them until data needs to be written to disk. However, this extra RAM usage may exceed your capacity. In such cases, you may want to use kraken-build's --work-on-disk switch. This will minimize the amount of RAM usage and cause Kraken's build programs to perform most operations off of disk files. This switch can also be useful for people building on a ramdisk or solid state drive. Please note that working off of disk files can be quite slow on some computers, causing builds to take several days if not weeks.
