### ISSUE TITLE
Hash size not specified, using '11236119640' :jellyfish::invertible_hash::ErrorAllocation

### ISSUE THREAD

**Issue by IshwaryaMullaiSelvapandian** [DerrickWood/kraken#67]
I am trying to build custom kraken database and i am getting the below issue.Can anyone help me with this?

I have followed the below steps:
kraken-build --download-taxonomy --db ninjatestdb/ish/efs/kraken/kraken
kraken-build --download-library bacteria --db ninjatestdb/ish/efs/kraken/kraken

[root@ip-10-**-**-*** kraken]# ./kraken-build --build --db ninjatestdb/ish/efs/kraken/kraken
Kraken build set to minimize disk writes.
Creating k-mer set (step 1 of 6)...
Found jellyfish v1.1.11
Hash size not specified, using '11236119640'
terminate called after throwing an instance of 'jellyfish::invertible_hash::ErrorAllocation'
  what():  Failed to allocate 91625968992 bytes of memory
xargs: cat: terminated by signal 13
/ish/efs/kraken/kraken/build_kraken_db.sh: line 96:  3180 Broken pipe             find library/ '(' -name '*.fna' -o -name '*.fa' -o -name '*.ffn' ')' -print0
      3181 Exit 125                | xargs -0 cat
      3182 Aborted                 | jellyfish count -m $KRAKEN_KMER_LEN -s $KRAKEN_HASH_SIZE -C -t $KRAKEN_THREAD_CT -o database /dev/fd/0

**Comment by Redmar-van-den-Berg** [comment]
The most important line is this:
`what(): Failed to allocate 91625968992 bytes of memory`
This indicates that jellyfish tried to reserve 91.6GB of RAM, which was not available. The simple workaround is the specify a hash size for kraken-build using `--jellyfish-hash-size`

**Comment by taltman** [comment]
Yep. Keep reducing that hash size by an order of magnitude until it fits snugly within your available RAM.

~T

**Comment by IshwaryaMullaiSelvapandian** [comment]
Thanks it worked after reducing the hash size.

**Comment by MaryoHg** [comment]
Good day, taltman and Ishwary.

I'm having the same issue trying to build the bacteria database.
I have only 32 GB of RAM and 12 cores.
I'm not sure which hash size value start with?
Would you mind help me? Please.

Thanks a lot.

**Comment by yangm9** [comment]
> 
> 
> Good day, taltman and Ishwary.
> 
> I'm having the same issue trying to build the bacteria database.
> I have only 32 GB of RAM and 12 cores.
> I'm not sure which hash size value start with?
> Would you mind help me? Please.
> 
> Thanks a lot.
Hi, Man,
I have try the command line as follow:
`conda run -n metawrap kraken-build --standard --threads 24 --jellyfish-hash-size 4000000 --db kraken`
Now, it is running, wait and see.
![图片](https://user-images.githubusercontent.com/55936864/85941589-67526300-b956-11ea-8986-0b6fda944506.png)

**Comment by taltman** [comment]
I would recommend that folks use Kraken2 unless there is some very specific use-case that Kraken (version 1) can handle better.

My $0.02.
