### ISSUE TITLE
kraken cannot use ncbi acession numbers

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [DerrickWood/kraken#68]
Dear @taltman and @DerrickWood

NCBI is phasing out Gene Identifiers (GI) numbers if favor of acession numbers. This is a problem for kraken, since it uses gi2taxid to assign taxonomy. 

I have tried to build a partial bacterial kraken database using both repositories (from @DerrickWood and @taltman), and in both cases the build process fails because the GI is lacking.

`
~/devel/taltman/kraken/installatie/kraken-build --db $KRAKEN_DB_NAME --build --threads 8
Kraken build set to minimize disk writes.
Skipping step 1, k-mer set already exists.
Skipping step 2, no database reduction requested.
Sorting k-mer set (step 3 of 6)...
K-mer set sorted. [3m34.424s]
Creating GI number to seqID map (step 4 of 6)...
report_gi_numbers.pl: sequence ID ref|NZ_CBML010000001.1| lacks GI number, aborting.
xargs: cat: terminated by signal 13
`

Did I do something wrong when building the database or is this indeed a problem with NCBI moving away from using GI's?

We use kraken a lot at my job, so I would be happy to contribute a fix for this if no one else is working on it. Please let me know if pull requests are appreciated.

**Comment by Redmar-van-den-Berg** [comment]
I found these scripts by @mw55309, which extract the taxid from the assembly statistics file hosted on ncbi together with the fasta files. I am currently working to integrate these into kraken, extracting the taxid from the statistics file should be a lot faster then parsing the giant acession to taxid mapping file.

https://github.com/mw55309/Kraken_db_install_scripts

**Comment by taltman** [comment]
Hi Redmar,

I am flattered to be included in this thread. I would be happy to take a look at a pull request that you might send over. I'm afraid that Derrick might be too busy at his new gig to maintain this repo, but I'll try to help where I can.

Could you specify which script you were looking at in @mw55309's repo?

Oh, and to be a pedantic bioinformaticst, GI actually stands for GenInfo Identifier, an old NCBI database. :-)
https://www.ncbi.nlm.nih.gov/Sitemap/sequenceIDs.html

**Comment by Redmar-van-den-Berg** [comment]
I was referring to this repository: https://github.com/mw55309/Kraken_db_install_scripts

In the end, I ended up not using those scripts since I'm not familiar with perl, and I found a way to completely bypass the gi-to-seqid and seqid-to-taxid mapping, which is computationally expensive.

It is still a work in progress, but both viral and bacterial genomes work now. I also sped up the download by using rsync, and no longer de-compress the fasta files to disk.

https://github.com/Redmar-van-den-Berg/kraken/tree/acession

I did not know about GenInfo Identifier, I guess I'll have to be even more pedantic an refer to them as G-I-I from now on.

**Comment by taltman** [comment]
Sounds like some serious improvements! Would be happy to review, time permitting.

@lynxoid pointed out that the Salzberg lab is working on a successor to Kraken, called Bracken, which might explain why Kraken hasn't been updated in a while...

**Comment by tseemann** [comment]
@taltman unfortunately Bracken still needs Kraken as the first step. it simply just uses a bayesian method to more specifically assign taxons. https://github.com/jenniferlu717/Bracken

I am told that Derrick has left academia for an industry job, so Kraken is probably now 'abandonware' unfortunately.   I think the community may be able to update it to support the loss of GI and strain-level-taxids.  I am working on some stuff too around this.

This file might be useful: ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/

I am currently using .GBK files and extracing `/db_xref="taxid:XXXX"` and sequence.

**Comment by tseemann** [comment]
@Redmar-van-den-Berg your use of `rsync` is great!  I am using Aspera `ascp` and the `--mode=diff` to do incremental batch updates. I still need to release the script.

**Comment by jenniferlu717** [comment]
Talked with Derrick and he created a fix for this issue. If you try the new Kraken version and it does not work, please let us know immediately, but this should be fixed now.
