### ISSUE TITLE
Support for Jellyfish v2.0

### ISSUE THREAD

**Issue by andzandz11** [DerrickWood/kraken#69]
How can I establish support between Kraken and Jellyfish 2.0?

**Comment by jenniferlu717** [comment]
I'm not sure about the details but after talking with Derrick Wood, its not possible for us to use Jellyfish 2.0 with Kraken. @fbreitwieser or @DerrickWood may be able to explain more.

**Comment by tseemann** [comment]
I'm assuming it's because @DerrickWood reads the actual database files at the `byte level` and the DB has changed for v2.   I'

```
jellyfish count -m $KRAKEN_KMER_LEN -s $KRAKEN_HASH_SIZE -C -t $KRAKEN_THREAD_CT  -o database /dev/fd/0
jellyfish merge -o database.jdb.tmp database_*

build_kraken_db.sh:      key_ct=$(perl -MFcntl -le 'open F, "database.jdb"; seek F, 48, SEEK_SET; read F, $b, 8; $a = unpack("Q", $b); print $a')
build_kraken_db.sh:      key_bits=$(perl -MFcntl -le 'open F, "database.jdb"; seek F, 8, SEEK_SET; read F, $b, 8; $a = unpack("Q", $b); print $a')
build_kraken_db.sh:      val_len=$(perl -MFcntl -le 'open F, "database.jdb"; seek F, 16, SEEK_SET; read F, $b, 8; $a = unpack("Q", $b); print $a')
```

**Comment by Kirk3gaard** [comment]
If you can install jelly-fish 1 in a different folder you can add it to the PATH variable to make sure kraken can access the correct version.

I did 
export PATH=/opt/jellyfish-1.1.11/bin:$PATH
and then kraken uses the specified version even though I have also jelly-fish 2 installed (I guess some other program uses the new version).

**Comment by tseemann** [comment]
@Kirk3gaard If you use Brew, I wrote the kraken recipe, and it installs a separate dedicates Jellyfish 1.1.1 to use, rather than the system one, which is usually 2.x

**Comment by jenniferlu717** [comment]
I have confirmed that we cannot use Jellyfish 2.0 for Kraken due to the way that Kraken uses the kmer information.

**Comment by conchoecia** [comment]
Why not just distribute jellyfish 1.0 with kraken? Many other programs require jellyfish 2, so I think it makes more sense to bundle jellyfish with kraken and compile them in the same folder rather than have the user change their PATH variable every time they want to use a different pipeline.

**Comment by your-highness** [comment]
Dear all,

I am working on kraken to use jellyfish v2. Mainly to be able to use k-mers longer than 31. Currently I am stuck in parsing the information `key_bits`, `val_len` and `key_ct` from the database file header: Jellyfish v1 used a a fixed number of field and Jellyfish v2 uses a JSON header. which is now in JSON format ([more information](https://lists.debian.org/debian-med/2015/11/msg00049.html)). I don't want to introduce any third party libraries for this task but read raw bits. You are welcome to contribute to the branch https://github.com/your-highness/kraken/tree/jellyfish-2 

Best

**Comment by jenniferlu717** [comment]
We are working on a new version of Kraken that actually eliminates the reliance on jellyfish entirely. The code is complete and in alpha testing now and we hope to release it soon but I do not have an exact release date yet.

**Comment by your-highness** [comment]
@jenniferlu717 Does this new version allow kmers > 31?

**Comment by Darkless012** [comment]
So does this mean that Kraken 1.1.1 doesn't require Jellyfish 1 anymore?

**Comment by jenniferlu717** [comment]
Kraken 2 (https://github.com/DerrickWood/kraken2/) is the updated version of Kraken that does not require Jellyfish. It allows for kmer lengths > 31. We are no longer updating Kraken 1.
