### ISSUE TITLE
Kraken Job - Loading database classify: unable to mmap /tes/krakendb/database.kdb: Cannot allocate memory

### ISSUE THREAD

**Issue by IshwaryaMullaiSelvapandian** [DerrickWood/kraken#71]
I have successfully built the kraken custom database using the below steps:

1.)kraken-build --download-taxonomy --db /test/krakendb/
2.)kraken-build --download-library bacteria --db /test/krakendb/
3.)kraken-build --build --db /test/krakendb/ --jellyfish-hash-size 200M

when I try to run the kraken job using the command 
"kraken --preload --db /test/krakendb --fastq-input --paired --output /test/Output/Test20150209-BandV_SyncTest_S1_ /test/Output/1_SyncTest_S1_PRS_pipeline_S1_L001_R1_001.fastq /test/Output/1_SyncTest_S1_PRS_pipeline_S1_L001_R2_001.fastq"

I get the below error:
Loading database... classify: unable to mmap /test/krakendb/database.kdb: Cannot allocate memory

Can anyone please tell me why I am getting this error?

**Comment by jenniferlu717** [comment]
how big is your database and how much memory do you have on your system?
