### ISSUE TITLE
Kraken needs a maintainer

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [DerrickWood/kraken#73]
As most of you are aware, kraken is essentially abandonware, even though it is still being used and developed, just not by the original maintainer. The result is that these improvements are scattered around github, and there is nobody that can merge them into the master code.

I propose we use this ticket to find a new maintainer, and for people to list the improvements they made to kraken that they would like to see merged. 

As far as I know, Kraken is used as a first step in [Bracken](https://github.com/jenniferlu717/Bracken), so perhaps @jenniferlu717 would be interested in taking over as maintainer for Derrick Wood.

**Comment by Redmar-van-den-Berg** [comment]
I have made kraken compatible with the new accession based naming scheme of NCBI. I would like to see this code included in Kraken, since the current download function is broken. The full changelog can be viewed here: https://github.com/Redmar-van-den-Berg/kraken/tree/accession

**Comment by jenniferlu717** [comment]
As the author of Bracken, I did not intend on taking over Kraken but our lab (myself and a couple of others) are working on some fixes to the removal of GI accession numbers.

@DerrickWood indicated to us that he does have a new version of Kraken he does want to release soon but we are unsure about when that may be. As a result, none of us are officially taking over maintenance of Kraken as of yet. 

We hope to release some fixes/updates or at least workarounds soon before the new version of Kraken is released. We have some other updates/changes to the source code that we have worked on however. 

I assure you that we have not abandoned the code as we do use Kraken ourselves quite often for our other projects.

**Comment by Redmar-van-den-Berg** [comment]
@jenniferlu717 Thanks for your response. I assumed nobody was working on kraken since the last commit was 2 years ago, but I'm glad to hear that people are working on it. I don't know how far your version of kraken has diverged from github, but feel free to take whatever you can use from the branch I linked, it is compatible with the latest version of NCBI.

**Comment by jenniferlu717** [comment]
Talked with Derrick and he wrote a fix for the phasing out of GI numbers. We are working through some of the other issues people have mentioned as needed/as appropriate. I'm going to go through the various branches and see which are easily integrated into the code and which may require more time on our end, although I don't know when the next update will be.

**Comment by Redmar-van-den-Berg** [comment]
@jenniferlu717 Thanks for getting things moving, I've seen a lot of activity in the last few weeks!
