### ISSUE TITLE
report_gi_numbers.pl: sequence ID NZ_CZEQ01000011.1 lacks GI number, aborting.

### ISSUE THREAD

**Issue by Jerry-kiwi** [DerrickWood/kraken#75]
Kraken 0.10.6 (talman fork)

www_adm@srv-bio:~/metagen/KRAKEN$ ./kraken-build --build --db /home/www_adm/metagen/KRAKEN_DB --jellyfish-hash-size 10000M --thread 24 --max-db-size 90 --new-db /home/www_adm/metagen/KRAKEN_DB90
Kraken build set to minimize disk writes.
Creating k-mer set (step 1 of 6)...
Found jellyfish v1.1.11
K-mer set created. [14h1m3.427s]
Reducing database size (step 2 of 6)...
Shrinking DB to use only 7337235796 of the 48055145119 k-mers
Wrote 7337235796/7337235796 k-mers to new file  
Database reduced. [49m6.953s]
Sorting k-mer set (step 3 of 6)...
K-mer set sorted. [1h56m13.277s]
Creating GI number to seqID map (step 4 of 6)...
**report_gi_numbers.pl: sequence ID NZ_CZEQ01000011.1 lacks GI number, aborting.**

Any help?
Tnahks in advance!

**Comment by jenniferlu717** [comment]
We just uploaded a fix to remove the Kraken dependence on GI numbers. Please try the new code and let us know if your issue is fixed? Thanks.

**Comment by Jerry-kiwi** [comment]
now error in step 5
No preliminary seqid|taxid mapping files found

**Comment by jenniferlu717** [comment]
What is your library structure?

**Comment by Jerry-kiwi** [comment]
/home/www_adm/metagen/KRAKEN_DB/library/Bacteria
bacteria.1.1.genomic.fna
....
bacteria.1024.1.genomic.fna

**Comment by jenniferlu717** [comment]
Sorry about this, but can you move all of those files to a staging directory and use the add-to-library option:

`for file in chr*.fa
do
    kraken-build --add-to-library $file --db $DBNAME
done`

**Comment by jenniferlu717** [comment]
See custom databases in https://ccb.jhu.edu/software/kraken/MANUAL.html. Part of the fix requires all library files to be added with that option, which creates intermediate files that helps in creating the seqid2taxid map file. 

Sorry about this. I'm going to try and update the manual fully to reflect these changes ASAP.

**Comment by jenniferlu717** [comment]
Working on making fixes. Sorry. Premature commit.

**Comment by Jerry-kiwi** [comment]
That's okay %) Thanks for help

**Comment by Jerry-kiwi** [comment]
By the way, if it possible to implement in the main repo dust mask from talman fork? sorry of offtop.

**Comment by jenniferlu717** [comment]
The GI number issue should be fixed. Not sure if we will be including dust in the main script because some people may dust their sequences before adding them to the database.

**Comment by ponomarevsy** [comment]
Sorry to jump in here... I getting this error, no matter what I do, when building databases using the latest release:

» kraken-build --standard --threads 16 --db /path/Kraken/0.10.6-foss-2016a-Perl-5.22.1/KRAKEN_DB --jellyfish-hash-size 1000M --work-on-disk
Found jellyfish v1.1.11
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 256 projects (381 sequences, 645.25 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 8950 projects (18482 sequences, 35.59 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 7493 projects (9458 sequences, 259.63 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Kraken build set to minimize RAM usage.
Creating k-mer set (step 1 of 6)...
Found jellyfish v1.1.11
K-mer set created. [1h42m4.565s]
Skipping step 2, no database reduction requested.
Sorting k-mer set (step 3 of 6)...
db_sort: unable to mmap database.jdb: Cannot allocate memory

Free command shows plenty of RAM available on the node:
» free
              total        used        free      shared  buff/cache   available
Mem:      264092792     7239592   224187536       50080    32665664   255611092
Swap:      16777212           0    16777212

Is there a workaround or is this a dead end? Thanks!

**Comment by Jerry-kiwi** [comment]
what is tehe size of database.jdb ?

**Comment by ponomarevsy** [comment]
Hi, Jerry-kiwi. Yesterday I tried building the database on a high memory node. This is what I have right now (is it complete or not??? Thanks!!!):

» ls -ltrh  /path/Kraken/0.10.6-foss-2016a-Perl-5.22.1/KRAKEN_DB
total 866G
drwxrwsr-x 2 appbuild appbuild 8.0K Sep 13 16:29 taxonomy
drwxrwsr-x 5 appbuild appbuild  512 Sep 13 16:48 library
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 11:43 database_0
-rw-rw-r-- 1 appbuild appbuild 9.1G Sep 14 11:44 database_1
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 11:46 database_2
-rw-rw-r-- 1 appbuild appbuild 8.8G Sep 14 11:47 database_3
-rw-rw-r-- 1 appbuild appbuild 8.8G Sep 14 11:48 database_4
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 11:50 database_5
-rw-rw-r-- 1 appbuild appbuild 9.0G Sep 14 11:51 database_6
-rw-rw-r-- 1 appbuild appbuild 9.3G Sep 14 11:52 database_7
-rw-rw-r-- 1 appbuild appbuild 9.1G Sep 14 11:53 database_8
-rw-rw-r-- 1 appbuild appbuild 9.0G Sep 14 11:55 database_9
-rw-rw-r-- 1 appbuild appbuild 9.1G Sep 14 11:56 database_10
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 11:57 database_11
-rw-rw-r-- 1 appbuild appbuild 8.8G Sep 14 11:59 database_12
-rw-rw-r-- 1 appbuild appbuild 8.8G Sep 14 12:00 database_13
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 12:01 database_14
-rw-rw-r-- 1 appbuild appbuild 8.7G Sep 14 12:02 database_15
-rw-rw-r-- 1 appbuild appbuild 8.9G Sep 14 12:04 database_16
-rw-rw-r-- 1 appbuild appbuild 8.7G Sep 14 12:05 database_17
-rw-rw-r-- 1 appbuild appbuild 9.0G Sep 14 12:06 database_18
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 12:07 database_19
-rw-rw-r-- 1 appbuild appbuild 8.8G Sep 14 12:09 database_20
-rw-rw-r-- 1 appbuild appbuild 8.5G Sep 14 12:10 database_21
-rw-rw-r-- 1 appbuild appbuild 9.0G Sep 14 12:11 database_22
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 12:12 database_23
-rw-rw-r-- 1 appbuild appbuild 8.9G Sep 14 12:14 database_24
-rw-rw-r-- 1 appbuild appbuild 9.1G Sep 14 12:15 database_25
-rw-rw-r-- 1 appbuild appbuild 9.1G Sep 14 12:16 database_26
-rw-rw-r-- 1 appbuild appbuild 9.1G Sep 14 12:17 database_27
-rw-rw-r-- 1 appbuild appbuild 9.1G Sep 14 12:19 database_28
-rw-rw-r-- 1 appbuild appbuild 8.6G Sep 14 12:20 database_29
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 12:21 database_30
-rw-rw-r-- 1 appbuild appbuild 656M Sep 14 12:21 database_31
-rw-rw-r-- 1 appbuild appbuild 155G Sep 14 13:23 database.jdb

**Comment by ponomarevsy** [comment]
So, as you can see, the database.jdb file is 155G but I don't see any .idx or .kdb files, though.

**Comment by Jerry-kiwi** [comment]
if i'm not mistaken, there was such problem earlier... and the main question -- is node itself and programs inside node can correctly determine amount of RAM (you use cluster, yer?)
just now i've making DB on machine with 128GB RAM and 256GM SSD swap. 
wil report results later, but i think it will be okay

![image](https://user-images.githubusercontent.com/8778463/30513505-0e7814ba-9b0d-11e7-85ac-739fd53a4f9a.png)

**Comment by ponomarevsy** [comment]
Did it finish? Yes, I was running kraken-build on the cluster node.

**Comment by Jerry-kiwi** [comment]
So, i've finish experiment.
Single PC with 128 GB RAM and 256GB swap located at SSD
./kraken-build --standard --threads 12 --db /home/www_adm/metagen/KRAKEN_DB_FULL  --jellyfish-hash-size 1000M

![2017-09-24 08 54 42](https://user-images.githubusercontent.com/8778463/30779875-10213b26-a106-11e7-9831-3de8527e0bac.png)

So, it seems, that your node connet correctly report about its memory.
I've used my fork of Kraken, but it's nearly the same, as original one.

**Comment by ponomarevsy** [comment]
Any suggestions on how to fix the memory issue? Thanks!

**Comment by ponomarevsy** [comment]
I've realized I can explicitly request more virtual memory, like so: qrsh -l highmem -l h_vmem=20G -pe fillup 16
This definitely makes a difference as I am on step 6/6 now:
```
» Found jellyfish v1.1.11
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 258 projects (386 sequences, 651.43 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 9277 projects (19160 sequences, 36.92 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 7536 projects (9542 sequences, 260.69 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Kraken build set to minimize RAM usage.
Skipping step 1, k-mer set already exists.
Skipping step 2, no database reduction requested.
Skipping step 3, k-mer set already sorted.
Skipping step 4, GI number to seqID map now obsolete.
Skipping step 5, seqID to taxID map already complete.
Setting LCAs in database (step 6 of 6)...
```
I hope this will finish successfully - I will let you know!

**Comment by ponomarevsy** [comment]
This has finished and now I have (Does that look complete? Thanks!):

» ls -ltrh KRAKEN_DB
total 1.2T
drwxrwsr-x 5 appbuild appbuild  512 Sep 13 16:48 library
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 11:43 database_0
-rw-rw-r-- 1 appbuild appbuild 9.1G Sep 14 11:44 database_1
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 11:46 database_2
-rw-rw-r-- 1 appbuild appbuild 8.8G Sep 14 11:47 database_3
-rw-rw-r-- 1 appbuild appbuild 8.8G Sep 14 11:48 database_4
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 11:50 database_5
-rw-rw-r-- 1 appbuild appbuild 9.0G Sep 14 11:51 database_6
-rw-rw-r-- 1 appbuild appbuild 9.3G Sep 14 11:52 database_7
-rw-rw-r-- 1 appbuild appbuild 9.1G Sep 14 11:53 database_8
-rw-rw-r-- 1 appbuild appbuild 9.0G Sep 14 11:55 database_9
-rw-rw-r-- 1 appbuild appbuild 9.1G Sep 14 11:56 database_10
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 11:57 database_11
-rw-rw-r-- 1 appbuild appbuild 8.8G Sep 14 11:59 database_12
-rw-rw-r-- 1 appbuild appbuild 8.8G Sep 14 12:00 database_13
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 12:01 database_14
-rw-rw-r-- 1 appbuild appbuild 8.7G Sep 14 12:02 database_15
-rw-rw-r-- 1 appbuild appbuild 8.9G Sep 14 12:04 database_16
-rw-rw-r-- 1 appbuild appbuild 8.7G Sep 14 12:05 database_17
-rw-rw-r-- 1 appbuild appbuild 9.0G Sep 14 12:06 database_18
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 12:07 database_19
-rw-rw-r-- 1 appbuild appbuild 8.8G Sep 14 12:09 database_20
-rw-rw-r-- 1 appbuild appbuild 8.5G Sep 14 12:10 database_21
-rw-rw-r-- 1 appbuild appbuild 9.0G Sep 14 12:11 database_22
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 12:12 database_23
-rw-rw-r-- 1 appbuild appbuild 8.9G Sep 14 12:14 database_24
-rw-rw-r-- 1 appbuild appbuild 9.1G Sep 14 12:15 database_25
-rw-rw-r-- 1 appbuild appbuild 9.1G Sep 14 12:16 database_26
-rw-rw-r-- 1 appbuild appbuild 9.1G Sep 14 12:17 database_27
-rw-rw-r-- 1 appbuild appbuild 9.1G Sep 14 12:19 database_28
-rw-rw-r-- 1 appbuild appbuild 8.6G Sep 14 12:20 database_29
-rw-rw-r-- 1 appbuild appbuild 9.2G Sep 14 12:21 database_30
-rw-rw-r-- 1 appbuild appbuild 656M Sep 14 12:21 database_31
-rw-rw-r-- 1 appbuild appbuild 155G Sep 14 13:23 database.jdb
-rw-rw-r-- 1 appbuild appbuild 8.1G Oct  3 15:28 database.idx
drwxrwsr-x 2 appbuild appbuild 8.0K Oct  3 18:03 taxonomy
-rw-rw-r-- 1 appbuild appbuild  17M Oct  3 18:03 seqid2taxid.map
-rw-rw-r-- 1 appbuild appbuild    0 Oct  3 18:03 accmap_file.tmp
-rw-rw-r-- 1 appbuild appbuild 155G Oct  4 17:06 database.kdb

**Comment by jenniferlu717** [comment]
It does look like your Kraken build worked succesfully.

**Comment by ponomarevsy** [comment]
Thank you, Jennifer!
