### ISSUE TITLE
Make a 0.11 release?

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken#79]
the recent changes suggest a new release be made
we need this for packaging purposes in brew and conda

see https://github.com/DerrickWood/kraken/issues/72

**Comment by datakid** [comment]
Would be great if it could be updated to use Jellyfish 2.x as well.

**Comment by tseemann** [comment]
@datakid this has been discussed here: https://github.com/DerrickWood/kraken/issues/69
