### ISSUE TITLE
Option "--report" for primary kraken script

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken#8]
Derrick,

Firstly, I just want to say that Kraken is a really nice piece of software, with good documentation and command line interface. Thank you!

I have an enhancement request. The typical use case is:

% kraken --db DB > kraken.out 
OR
% kraken --db DB --outfile kraken.out
THEN
% kraken-report --db DB kraken.out > kraken.report

I was thinking an option like this:

% kraken --db DB --outfile kraken.out --report kraken.report --mpa-report kraken.mpa

That way the user doesn't have to RE-specify the --db parameter, and the user-end result is available in one command.

(Maybe a --filter option as well in case that makes sense wrt kraken-filter)

Torsten

**Comment by DerrickWood** [comment]
Hi Torsten,

Apologies for the late response here. I think I'm going to hold off a bit on this particular feature, as the two report scripts have extra options (and may have more in the future) that I wouldn't want to mix with the main kraken wrapper's option handling.

I'm hoping the introduction of the KRAKEN_DEFAULT_DB environment variable might make this situation a little less troublesome, though.

**Comment by tseemann** [comment]
Your reasoning is good, and the variables make this much simpler. Thanks!
