### ISSUE TITLE
Can we use JF 1.1.6 instead of 1.1.1 ?

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken#80]
The current version of JELLYFISH is 1.1.6

I know we can't use 2.x but can we use a newer 1.x ?

**Comment by Jerry-kiwi** [comment]
The last version of JELLYFISH 1 is 1.1.11.

**Comment by jenniferlu717** [comment]
We use version Jellyfish 1.1.10. It would be fine to use a newer 1.x

**Comment by tseemann** [comment]
@Jerry-kiwi good point - i messed up. I am using 1.1.11  -- too many 1's !
