### ISSUE TITLE
Merging pairs with 'N' makes it hard to un-pair in --[un]classified

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken#84]
Currently when `--paired R1 R2` is used, it uses a perl script to combine pairs into a single psuedo-read as `R1 - N - R2`, and Kraken ignores kmers with `N` in them to avoid chimera classifications.

However, the `--classified-out` and `--unclassified-out` return the merged sequences with the `N` still in them.

To unpair them, one would normally just split on the `N`.  But...
* there could other existing "real" `N` in the sequence
* can't choose the middle `N` because pairs aren't always the same length

Not sure what best solution is, but perhaps using 'X' or something not in the DNA IUPAC library would be better.

It would be good if `--[un]classified-out` could take a file prefix, and when in `--paired` mode they could output `prefix_R1.fq` and `prefix_R2.fq` or the user could supply.

Even better if `--out-fmt` could be `legacy`, `interleaved` or `paired/prefix` ?

**Comment by dfornika** [comment]
I took a crack at this in pull request #85.

**Comment by jenniferlu717** [comment]
Merged in @dfornika 's code! should work now

**Comment by tseemann** [comment]
Thanks @dfornika and @jenniferlu717 !
