### ISSUE TITLE
Does kraken-build build require downloading?

### ISSUE THREAD

**Issue by datakid** [DerrickWood/kraken#86]
I'm building a custom Kraken DB. Unfortunately our HPC is behind a relatively strict firewall, so there's no ability to download content. 

I've got an offsite server for this purpose in an OpenStack environment that only allows for 64GB of memory. 

I've (I think) downloaded everything required by `kraken-build --download-taxonomy` and `kraken-build --download-library`

I am up to the --build stage, but the jellyfish keeps dying because it runs out of memory. I have machines in house that have 364GB of memory - but they are behind the firewall.

Does the --build phase require any ability to download extra data?

**Comment by jenniferlu717** [comment]
If you have your library and your taxonomy, the actual build will not require any additional downloads.

**Comment by datakid** [comment]
Great, thanks.
