### ISSUE TITLE
Link to Bracken is broken

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken#88]
In the manual:

For abundance estimation with Kraken results, refer to Bracken, which estimations species/genus-level abundance from Kraken classification results.

https://ccb.jhu.edu/software/Bracken/

Not Found

The requested URL /software/Bracken/ was not found on this server.

Apache/2.2.3 (Scientific Linux) Server at ccb.jhu.edu Port 443

**Comment by jenniferlu717** [comment]
Sorry it's not meant to be capitalized. I will fix the manual today.
