### ISSUE TITLE
Environmental variables for default --db and --threads

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken#9]
Specifying the full --db path and --threads each time is a bit tedious. What would you think about having (optional) environment variables for these defaults:

KRAKEN_DB_DEFAULT=/usr/local/share/kraken/db/mini_kraken
KRAKEN_THREADS_DEFAULT=8

Yes, I could write a wrapper script for these for the typical user. If I get time I could generate a pull request, but until then this Issue report will remind me.

**Comment by DerrickWood** [comment]
Done. :)

Well, it's "KRAKEN_DEFAULT_DB" and "KRAKEN_NUM_THREADS", but it's close.
