### ISSUE TITLE
Building of standard database stops due to segmentation fault/broken pipe while "Setting LCAs in database (step 6 of 6)"

### ISSUE THREAD

**Issue by flopezo** [DerrickWood/kraken#91]
Hello,

I'm trying to build the standard database using Kraken v1.0, but it stops during step 6:

`Setting LCAs in database (step 6 of 6)...`
`xargs: cat: terminated by signal 13`
`build_kraken_db.sh: line 204: 28665 Done                    find library/ '(' -name '*.fna' -o -name '*.fa' -o -name '*.ffn' ')' -print0`
     `28666 Exit 125                | xargs -0 cat`
     `28667 Segmentation fault      | set_lcas $MEMFLAG -x -d database.kdb -i database.idx -n taxonomy/nodes.dmp -t $KRAKEN_THREAD_CT -m seqid2taxid.map -F /dev/fd/0`

Any help would be greatly appreciated.

**Comment by jenniferlu717** [comment]
What command line did you use?

**Comment by flopezo** [comment]
`kraken-build --standard --threads 16 --db /path/to/db`

I also tried with `--threads 1`.

**Comment by flopezo** [comment]
I used `kraken-build --threads 16 --standard --db /path/to/db`

Thank you!

**Comment by flopezo** [comment]
I was able to successfully build a database using only the archaea and viral genomic libraries. However, when I added the library for bacteria (`kraken-build --download-library bacteria`), the database building process failed again during step 6 due to a segmentation fault.

**Comment by jenniferlu717** [comment]
There may just be some non-fasta file in your bacteria library folder that is causing this issue but I don't know exactly why this is happening. I was able to build the standard database myself without errors multiple times....

**Comment by jenniferlu717** [comment]
Hi, I was talking to someone else that works also on kraken databases and he suggested that the segmentation fault might just be due to the RAM usage of the database but we don't quite have a solution for it. I'm going to talk to Derrick Wood to see if there is some other solution.

**Comment by flopezo** [comment]
Thank you for your help, Jennifer.

**Comment by pvishwa2** [comment]
What was the solution to this issue?
I'm still facing this problem, but haven't had any luck finishing the build using the solutions listed (upping RAM, re-downloading library).

**Comment by feifeiyang123** [comment]
Hi, I had a same error when build standard database: 
Kraken build set to minimize disk writes.
Creating k-mer set (step 1 of 6)...
Found jellyfish v1.1.10
xargs: cat: terminated by signal 13

How can I fit it? Please help me!

**Comment by jkin2003** [comment]
same error output different step:
Step 2/2: Assigning taxonomic IDs to sequences
All files processed, cleaning up extra sequence files... done, library complete.
Downloading UniVec_Core data from server... done.
Adding taxonomy ID of 28384 to all sequences... done.
Masking low-complexity regions of downloaded library... done.
Creating sequence ID to taxonomy ID map (step 1)...
Sequence ID to taxonomy ID map already present, skipping map creation.
Estimating required capacity (step 2)...
/work/k/kinskeyj/KrakenDownload/kraken2/scripts/build_kraken2_db.sh: line 101: estimate_capacity: command not found
xargs: cat: terminated by signal 1
