### ISSUE TITLE
read_merger.pl: must specify exactly one of FASTA and FASTQ input flags

### ISSUE THREAD

**Issue by Rebeccabengtsson** [DerrickWood/kraken#95]
Hi, 

When im using read_merger.pl 

`[v1rbeng2@login03(eddie) 1886]$ kraken/read_merger.pl 1886.for.trimmed.paired.fq.gz 1886.rev.trimmed.paired.fq.gz`

I get the following error 

`read_merger.pl: must specify exactly one of FASTA and FASTQ input flags`

Can you tell me what i'm doing wrong? There is no -h for this script

Thanks 
Rebecca

**Comment by jenniferlu717** [comment]
What exactly are you trying to do with these reads? Are you trying to concatenate them?

**Comment by jenniferlu717** [comment]
the read_merger.pl script is used by kraken to output classified/unclassified reads as either concatenated pairs or unconcatenated pairs when specifying the classified or unclassified output flags with the --paired flag. But if you are just trying to concatenate the pairs, I can look into the exact command line for it.

**Comment by Rebeccabengtsson** [comment]
I want to concatenate the paired reads into a single file as input for kraken, I have used seqtk to do so and it works fine.
