### ISSUE TITLE
Rerun the analysis with Kraken v1.0?

### ISSUE THREAD

**Issue by lconteville** [DerrickWood/kraken#96]
Hi, 
I have a bunch of data analyzed with kraken-0.10.5-beta, but I see now that Kraken is v1.0.
Should I rerun the analysis? If I use the same database as before, am I going to get the same results?

Thank you in advance,

Liliane

**Comment by jenniferlu717** [comment]
The actual algorithm has not changed. We finally released Kraken. V1.0 after making adjustments to database building and removing the reliance on gi numbers. 

You will get the same results so I would not rerun your analysis.
