### ISSUE TITLE
Problem with out-fmt and fastq-output

### ISSUE THREAD

**Issue by tangminBio** [DerrickWood/kraken#98]
Hello,

I am using kraken-1.0. Here is my command line:
kraken --preload --db kk-s-base R1.fq.gz R2.fq.gz --paired --fastq-input --gzip-compressed --threads 28 --classified-out test.assigned --unclassified-out  test.unassigned --out-fmt paired --fastq-output --output test.kraken
And I got error as follows:
Unknown option: out-fmt
Unknown option: fastq-output
kraken: --paired requires exactly two filenames

**Comment by jenniferlu717** [comment]
Hi, apologies, I should have made it clearer in the manual about how to run the paired reads. The --out-fmt option was added for the newest version of kraken. It wasn't part of the first release and I think I forgot to update the version number when I merged in unpairing. Can you first try redownloading the software?  
When trying to use the --out-fmt paired option, you need to list the two paired reads after all of the other options.

**Comment by tangminBio** [comment]
Hi Derrick,

Thank you for getting back on this.
I redownloaded the V1.0 (zip source code on https://github.com/DerrickWood/kraken/releases/tag/v1.0)
But still with no option of out-fmt

“Usage: kraken [options] <filename(s)>

Options:
  --db NAME               Name for Kraken DB
                          (default: none)
  --threads NUM           Number of threads (default: 1)
  --fasta-input           Input is FASTA format
  --fastq-input           Input is FASTQ format
  --gzip-compressed       Input is gzip compressed
  --bzip2-compressed      Input is bzip2 compressed
  --quick                 Quick operation (use first hit or hits)
  --min-hits NUM          In quick op., number of hits req'd for classification
                          NOTE: this is ignored if --quick is not specified
  --unclassified-out FILENAME
                          Print unclassified sequences to filename
  --classified-out FILENAME
                          Print classified sequences to filename
  --output FILENAME       Print output to filename (default: stdout); "-" will
                          suppress normal output
  --only-classified-output
                          Print no Kraken output for unclassified sequences
  --preload               Loads DB into memory before classification
  --paired                The two filenames provided are paired-end reads
  --check-names           Ensure each pair of reads have names that agree
                          with each other; ignored if --paired is not specified
  --help                  Print this message
  --version               Print version information

If none of the *-input or *-compressed flags are specified, and the
file is a regular file, automatic format detection is attempted.”

Best,
Min

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: jenniferlu717 <notifications@github.com>
发送时间: Tuesday, December 5, 2017 3:56:31 PM
收件人: DerrickWood/kraken
抄送: tangminBio; Author
主题: Re: [DerrickWood/kraken] Problem with out-fmt and fastq-output (#98)


Hi, apologies, I should have made it clearer in the manual about how to run the paired reads. The --out-fmt option was added for the newest version of kraken. It wasn't part of the first release and I think I forgot to update the version number when I merged in unpairing. Can you first try redownloading the software?
When trying to use the --out-fmt paired option, you need to list the two paired reads after all of the other options.

―

**Comment by jenniferlu717** [comment]
Oh it wasn't in the newest tagged release, just in the main source code. I added a new release for version 1.1 and that will include the --out-fmt paired options

-Jennifer Lu
